"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { GrantViewModel } from "../../lib/domain/types.ts";
import { categoryTaxonomy, facilityTaxonomy } from "../../lib/domain/grant-view-model.ts";
import { emptyExplorerFilters, explorerEmptyState, explorerFilterChips, explorerRegions, explorerStatuses, hasPublicExplorerControls, matchesExplorerFilters, parseExplorerQuery, removeExplorerFilterChip, serializeExplorerQuery, sortExplorerGrants, type ExplorerFilterState, type ExplorerSort } from "../../lib/domain/explorer-filter.ts";
import { supportTypeLabel, supportTypeValues } from "../../lib/domain/support-types.ts";
import type { ExternalResourceType } from "../../lib/domain/types.ts";
import { useSavedGrantIds } from "./saved-grants.tsx";
import { DataPrincipleDialog } from "./DataPrincipleDialog";

const regions=explorerRegions.filter(value=>value!=="확인 필요");
const facilities=facilityTaxonomy.filter(value=>value!=="확인 필요");
const categories=categoryTaxonomy.filter(value=>value!=="확인 필요");
const statuses=explorerStatuses.filter(value=>value!=="일정 확인 필요");

export function ExplorerClient({grants,activeSourceCount}:{grants:GrantViewModel[];activeSourceCount:number}){
  const [filters,setFilters]=useState<ExplorerFilterState>(emptyExplorerFilters);const [sort,setSort]=useState<ExplorerSort>("deadline");const [sheet,setSheet]=useState(false);const [ready,setReady]=useState(false);const{savedIds,toggle}=useSavedGrantIds();const filterTriggerRef=useRef<HTMLButtonElement>(null);const filterCloseRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const sync=()=>setFilters(parseExplorerQuery(window.location.search));const timeout=window.setTimeout(()=>{sync();setReady(true);},0);window.addEventListener("popstate",sync);return()=>{window.clearTimeout(timeout);window.removeEventListener("popstate",sync);};},[]);
  useEffect(()=>{if(!ready)return;const query=serializeExplorerQuery(filters);const next=query?`/?${query}`:"/";if(`${window.location.pathname}${window.location.search}`!==next)history.pushState(null,"",next);},[filters,ready]);
  const setSearch=(search:string)=>setFilters(old=>({...old,search}));const setRegion=(region:string)=>setFilters(old=>({...old,region}));
  const toggleFilter=useCallback((key:"facility"|"category"|"status"|"support",value:string)=>setFilters(old=>{const values=old[key] as string[];return{...old,[key]:values.includes(value)?values.filter(item=>item!==value):[...values,value]};}),[]);
  const filtered=useMemo(()=>grants.filter(grant=>matchesExplorerFilters(grant,filters)),[grants,filters]);
  const visible=useMemo(()=>sortExplorerGrants(filtered,sort),[filtered,sort]);
  const count=(kind:"region"|"facility"|"category"|"status"|"support",value:string)=>grants.filter(grant=>kind==="region"?(value==="전체"||grant.eligibleRegion===value||(value!=="전국"&&value!=="확인 필요"&&grant.eligibleRegion==="전국")):kind==="facility"?grant.facilityTypes.includes(value):kind==="category"?grant.field===value:kind==="status"?grant.status===value:grant.supportTypes.includes(value as ExternalResourceType)).length;
  const closeSheet=useCallback(()=>{setSheet(false);requestAnimationFrame(()=>filterTriggerRef.current?.focus());},[]);
  useEffect(()=>{if(!sheet)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";filterCloseRef.current?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==="Escape")closeSheet();};document.addEventListener("keydown",keydown);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",keydown);};},[sheet,closeSheet]);
  const reset=()=>setFilters(emptyExplorerFilters);const chips=explorerFilterChips(filters);const zero=explorerEmptyState(activeSourceCount);const hasPublicGrants=hasPublicExplorerControls(grants.length);
  return <>
    {hasPublicGrants?<div className="mobile-filterbar"><button ref={filterTriggerRef} type="button" aria-expanded={sheet} aria-controls="mobile-filter-sheet" onClick={()=>setSheet(true)}>필터 {chips.length?`${chips.length}개 적용`:"선택"} ▾</button><span>지원사업 공고 <b>{visible.length}</b>건</span></div>:null}
    <div className={`explorer-shell ${hasPublicGrants?"":"zero-public"}`}>
      {hasPublicGrants?<aside className="filters" aria-label="공고 필터"><SearchField value={filters.search} onChange={setSearch}/><FilterControls filters={filters} setRegion={setRegion} toggle={toggleFilter} count={count}/><button className="reset" type="button" onClick={reset}>검색·필터 초기화</button></aside>:null}
      <main className="results" id="grants">
        {hasPublicGrants?<><div className="result-bar"><h2 aria-live="polite">지원사업 공고 <strong>{visible.length}</strong>건</h2><div className="sort" aria-label="정렬"><button type="button" className={sort==="deadline"?"active":undefined} aria-pressed={sort==="deadline"} onClick={()=>setSort("deadline")}>마감 임박순</button><button type="button" className={sort==="recent"?"active":undefined} aria-pressed={sort==="recent"} onClick={()=>setSort("recent")}>최근 수집순</button></div></div><div className="desktop-search"><SearchField value={filters.search} onChange={setSearch}/></div><div className="selected-chips" aria-label="선택된 검색과 필터">{chips.length?chips.map(chip=><button key={`${chip.key}-${chip.value}`} onClick={()=>setFilters(old=>removeExplorerFilterChip(old,chip))}>{chip.label}<b>×</b></button>):<span>전체</span>}</div></>:null}
        {visible.length?<div className="grant-list">{visible.map(grant=><GrantCard grant={grant} saved={savedIds.includes(grant.id)} onSave={()=>toggle(grant.id)} key={grant.id}/>)}</div>:grants.length===0?<div className="empty-state"><h3>{zero.heading}</h3><p>{zero.body}</p><DataPrincipleDialog triggerLabel="데이터 원칙 보기" triggerClassName="empty-principle-trigger"/></div>:<div className="empty-state"><h3>검색 조건에 맞는 공고가 없습니다.</h3><p>검색어나 필터를 지우면 공개 공고 {grants.length}건을 볼 수 있습니다.</p><button onClick={reset}>전체 공고 보기</button></div>}
      </main>
    </div>
    {hasPublicGrants&&sheet?<div className="sheet-backdrop" role="presentation" onClick={event=>{if(event.target===event.currentTarget)closeSheet();}}><section id="mobile-filter-sheet" className="filter-sheet" role="dialog" aria-modal="true" aria-label="모바일 공고 필터"><div className="sheet-handle"/><div className="sheet-head"><h2>공고 검색·필터</h2><button ref={filterCloseRef} type="button" aria-label="필터 닫기" onClick={closeSheet}>×</button></div><SearchField value={filters.search} onChange={setSearch}/><FilterControls filters={filters} setRegion={setRegion} toggle={toggleFilter} count={count}/><button type="button" className="sheet-apply" onClick={closeSheet}>공고 {visible.length}건 보기</button></section></div>:null}
  </>;
}

function SearchField({value,onChange}:{value:string;onChange:(value:string)=>void}){return <label className="search-field"><span>공고 검색</span><div><span aria-hidden="true">⌕</span><input type="search" value={value} onChange={event=>onChange(event.target.value)} placeholder="공고명 또는 주관기관명" autoComplete="off"/><button type="button" aria-label="검색어 지우기" hidden={!value} onClick={()=>onChange("")}>×</button></div></label>}
function FilterControls({filters,setRegion,toggle,count}:{filters:ExplorerFilterState;setRegion:(value:string)=>void;toggle:(key:"facility"|"category"|"status"|"support",value:string)=>void;count:(kind:"region"|"facility"|"category"|"status"|"support",value:string)=>number}){return <><fieldset className="filter-group"><legend>지원 가능 지역</legend>{regions.map(value=><label className={filters.region===value?"selected":""} key={value}><input type="radio" name="region" checked={filters.region===value} onChange={()=>setRegion(value)}/><span>{value}</span><small>{count("region",value)}</small></label>)}</fieldset><CheckGroup title="지원형태" values={supportTypeValues} selected={filters.support} label={value=>supportTypeLabel(value as ExternalResourceType)} onToggle={value=>toggle("support",value)} count={value=>count("support",value)}/><CheckGroup title="시설유형" values={facilities} selected={filters.facility} onToggle={value=>toggle("facility",value)} count={value=>count("facility",value)}/><CheckGroup title="지원분야" values={categories} selected={filters.category} onToggle={value=>toggle("category",value)} count={value=>count("category",value)}/><CheckGroup title="접수 상태" values={statuses} selected={filters.status} onToggle={value=>toggle("status",value)} count={value=>count("status",value)}/></>}
function CheckGroup({title,values,selected,onToggle,count,label=(value)=>value}:{title:string;values:readonly string[];selected:readonly string[];onToggle:(value:string)=>void;count:(value:string)=>number;label?:(value:string)=>string}){return <fieldset className="filter-group"><legend>{title}</legend>{values.map(value=><label className={selected.includes(value)?"selected":""} key={value}><input type="checkbox" checked={selected.includes(value)} onChange={()=>onToggle(value)}/><span>{label(value)}</span><small>{count(value)}</small></label>)}</fieldset>}

export function GrantCard({grant,saved,onSave}:{grant:GrantViewModel;saved:boolean;onSave:()=>void}){const unknown=grant.statusTone==="check"||grant.eligibilityTone!=="verified";const deadlineState=grant.dDay??(grant.status==="마감"?"마감":"일정 확인 필요");const hasAmount=grant.amountLabel!=="확인 필요";const hasSelfBurden=grant.selfBurdenLabel!=="확인 필요";return <article className={`grant-card ${unknown?"unknown":""}`}><Link className="card-main-link" href={`/grants/${grant.id}`} aria-label={`${grant.title} 상세 보기`}><span/></Link><div className="card-top"><span className={`status ${grant.statusTone}`}>{grant.status}</span><strong className={`dday ${!grant.dDay&&grant.status!=="마감"?"unknown-value":""}`}>{deadlineState}</strong><button type="button" className={`save-button ${saved?"saved":""}`} aria-pressed={saved} onClick={onSave}>{saved?"★ 저장됨":"☆ 저장"}</button></div>{grant.supportTypes.length?<div className="support-type-row" aria-label="지원형태">{grant.supportTypes.map(type=><span className="support-type-tag" key={type}>{supportTypeLabel(type)}</span>)}</div>:null}<div className="card-body"><div className="card-copy"><h3>{grant.title}</h3><p className="organization">{grant.organization} · 출처 {grant.sourceName}</p><div className="card-meta-row" aria-label="공고 분류와 신청대상 확인 상태"><span className="tag">{grant.eligibleRegion}</span><span className="tag field-tag">{grant.field}</span><span className={`tag eligibility ${grant.eligibilityTone!=="verified"?"needs-review":""}`}>{grant.eligibilityLabel}</span></div><p className={`evidence ${unknown?"evidence-unknown":""}`}><strong>{grant.evidenceText}</strong></p></div><div className="summary-panel"><Summary label="신청 마감" value={grant.dateLabel}/>{hasAmount?<Summary label="지원금" value={grant.amountLabel}/>:null}{hasSelfBurden?<Summary label="자부담" value={grant.selfBurdenLabel}/>:null}<Link className="source-link" href={grant.sourceUrl} target="_blank" rel="noopener noreferrer">공식 공고 확인 ↗</Link></div></div></article>}
function Summary({label,value}:{label:string;value:string}){return <div className="summary-row"><span>{label}</span><strong className={value.includes("확인 필요")?"unknown-value":""}>{value}</strong></div>}
