import assert from "node:assert/strict";
import test from "node:test";
import { strToU8, zipSync } from "fflate";
import type { D1DatabaseLike } from "../lib/cloudflare.ts";
import { detectAttachmentFormat } from "../lib/attachments/file-type.ts";
import { extractHwpx, extractZipChildren, parseAttachmentBytes } from "../lib/attachments/parsers.ts";
import { applyAttachmentEvidence, extractAttachmentEvidence } from "../lib/attachments/verification.ts";
import { attachmentContentHash, processAttachmentMessage } from "../lib/attachments/pipeline.ts";
import type { ExtractionArtifact } from "../lib/attachments/contracts.ts";

function pdf(text:string){const escaped=text.replace(/([\\()])/g,"\\$1");const stream=text?`BT /F1 12 Tf 72 720 Td (${escaped}) Tj ET`:"";const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];let output="%PDF-1.4\n";const offsets=[0];objects.forEach((object,index)=>{offsets.push(output.length);output+=`${index+1} 0 obj\n${object}\nendobj\n`;});const xref=output.length;output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(output);}
function hwpx(){const section=`<?xml version="1.0" encoding="UTF-8"?><hp:section xmlns:hp="urn:hancom:section"><hp:p><hp:run><hp:t>신청기간 2026년 9월 1일 09:00 ~ 2026년 9월 18일 18:00까지</hp:t></hp:run></hp:p><hp:tbl><hp:tr><hp:tc><hp:p><hp:run><hp:t>신청대상 서울 소재 청소년수련시설 및 청소년문화의집</hp:t></hp:run></hp:p></hp:tc></hp:tr></hp:tbl></hp:section>`;return zipSync({mimetype:strToU8("application/hwp+zip"),"Contents/section0.xml":strToU8(section)});}
function artifact(role:"PRIMARY"|"FORM",blocks:{location:string;text:string}[]):ExtractionArtifact{return{version:"attachment-v1",attachmentId:"att-1",filename:role==="FORM"?"신청서 양식.hwpx":"모집공고.hwpx",format:"HWPX",role,blocks,metadata:{}};}
function fakeDb(row:Record<string,unknown>){const writes:{query:string;values:unknown[]}[]=[];const db={prepare(query:string){let values:unknown[]=[];return{bind(...next:unknown[]){values=next;return this;},async first(){return row;},async all(){return{results:[]};},async run(){writes.push({query,values});return{meta:{changes:1}};}};},async batch(){return[];}} as unknown as D1DatabaseLike;return{db,writes};}

test("MIME and magic bytes reject a PDF-named HTML error page",()=>{const detected=detectAttachmentFormat(new TextEncoder().encode("<html>denied</html>"),"notice.pdf","text/html");assert.equal(detected.format,"UNSUPPORTED");assert.equal(detected.mismatch,true)});
test("content hash is stable and changes with bytes",async()=>{assert.equal(await attachmentContentHash(strToU8("same")),await attachmentContentHash(strToU8("same")));assert.notEqual(await attachmentContentHash(strToU8("same")),await attachmentContentHash(strToU8("other")))});
test("HWPX extracts paragraph and table text with section provenance",()=>{const blocks=extractHwpx(hwpx());assert.ok(blocks.some(block=>block.text.includes("2026년 9월 18일")));assert.ok(blocks.some(block=>block.text.includes("청소년문화의집")));assert.ok(blocks.every(block=>block.location.startsWith("section 1")));assert.throws(()=>extractHwpx(zipSync({"random.xml":strToU8("<x/>")})),/HWPX_PACKAGE_INVALID/)});
test("PDF text layer parses while an empty PDF becomes OCR_REQUIRED",async()=>{const normal=await parseAttachmentBytes({attachmentId:"pdf-1",filename:"notice.pdf",format:"PDF",role:"PRIMARY",bytes:pdf("Application deadline 2026-09-18 18:00"),archiveDepth:0});assert.equal(normal.status,"PARSED");assert.ok(normal.artifact?.blocks[0].text.includes("2026-09-18"));const scanned=await parseAttachmentBytes({attachmentId:"pdf-2",filename:"scan.pdf",format:"PDF",role:"PRIMARY",bytes:pdf(""),archiveDepth:0});assert.equal(scanned.status,"OCR_REQUIRED")});
test("ZIP accepts supported children and blocks traversal and nested recursion",async()=>{const safe=zipSync({"docs/notice.pdf":pdf("Deadline")});assert.equal(extractZipChildren(safe).length,1);const malicious=zipSync({"../evil.pdf":pdf("x")});assert.throws(()=>extractZipChildren(malicious),/ZIP_PATH_TRAVERSAL/);const nested=await parseAttachmentBytes({attachmentId:"zip-1",filename:"nested.zip",format:"ZIP",role:"SUPPORTING",bytes:safe,archiveDepth:1});assert.equal(nested.status,"PARSE_FAILED");assert.equal(nested.errorCode,"ZIP_DEPTH_LIMIT")});
test("HWP and image failures are explicit non-fatal states",async()=>{const hwp=await parseAttachmentBytes({attachmentId:"hwp-1",filename:"form.hwp",format:"HWP",role:"FORM",bytes:new Uint8Array([0xd0,0xcf]),archiveDepth:0});assert.equal(hwp.status,"HWP_PARSER_BLOCKED");const image=await parseAttachmentBytes({attachmentId:"img-1",filename:"poster.png",format:"PNG",role:"MEDIA",bytes:new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]),archiveDepth:0});assert.equal(image.status,"OCR_REQUIRED")});
test("attachment evidence recovers deadline and eligibility but FORM examples are ignored",()=>{const primary=artifact("PRIMARY",[{location:"section 1 · paragraph 1",text:"신청기간 2026년 9월 1일 09:00 ~ 2026년 9월 18일 18:00까지"},{location:"section 1 · paragraph 2",text:"신청대상 서울 소재 청소년수련시설 및 청소년문화의집"}]);const evidence=extractAttachmentEvidence(primary);assert.equal(evidence.length,2);assert.equal(evidence.find(item=>item.field==="deadline")?.value,"2026-09-18T18:00:00+09:00");assert.deepEqual(evidence.find(item=>item.field==="eligibility")?.value,["청소년수련시설","청소년문화의집"]);assert.equal(extractAttachmentEvidence(artifact("FORM",primary.blocks)).length,0)});
test("institution support amount is separated from total budget and self burden is preserved",()=>{const evidence=extractAttachmentEvidence(artifact("PRIMARY",[{location:"section 2 · paragraph 4",text:"총사업비 5억원이며 선정 기관당 최대 2,000만원 지원, 자부담 없음"}]));assert.equal(evidence.find(item=>item.field==="amount")?.value,20_000_000);assert.equal(evidence.find(item=>item.field==="self_burden")?.value,"없음")});
test("BODY and attachment deadline conflict stays REVIEW_REQUIRED",async()=>{const{db,writes}=fakeDb({id:"opp-1",deadline:"2026-09-17T18:00:00+09:00",deadline_verification:"VERIFIED",deadline_evidence:"본문 접수 마감",eligibility_verification:"UNKNOWN",eligibility_evidence:null,facility_types_json:'["기타 / 확인 필요"]',review_status:"REVIEW_REQUIRED"});const result=await applyAttachmentEvidence(db,"raw-1",[{field:"deadline",value:"2026-09-18T18:00:00+09:00",evidenceText:"접수 마감 2026년 9월 18일 18:00",attachmentId:"att-1",filename:"공고문.pdf",location:"page 3",sourceType:"ATTACHMENT"}]);assert.equal(result.conflict,true);assert.ok(writes.some(write=>write.values.includes("REVIEW_REQUIRED")))});
test("final attachment is not downloaded twice and fetch failure is recorded",async()=>{let fetches=0;const base={id:"att-1",raw_notice_id:"raw-1",source_id:"s",source_run_id:null,parent_attachment_id:null,name:"notice.pdf",url:"https://example.com/notice.pdf",content_type:"application/pdf",extension:"pdf",document_role:"PRIMARY",priority:100,fetch_status:"FETCHED",parse_status:"PARSED",content_hash:"abc",r2_key:"key",archive_depth:0};const final=fakeDb(base);const skipped=await processAttachmentMessage({DB:final.db},{attachmentId:"att-1",rawNoticeId:"raw-1",sourceId:"s",url:"https://example.com/notice.pdf"},async()=>{fetches++;return new Response()});assert.equal(skipped.status,"SKIPPED");assert.equal(fetches,0);const failed=fakeDb({...base,id:"att-2",parse_status:"PENDING",content_hash:null,r2_key:null});await assert.rejects(()=>processAttachmentMessage({DB:failed.db,ATTACHMENTS:{get:async()=>null,head:async()=>null,put:async()=>({})}},{attachmentId:"att-2",rawNoticeId:"raw-1",sourceId:"s",url:"https://example.com/fail.pdf"},async()=>new Response("fail",{status:503})),/ATTACHMENT_HTTP_503/);assert.ok(failed.writes.some(write=>write.values.includes("ATTACHMENT_HTTP_503")))});
test("forced reprocessing reads the preserved R2 original instead of upstream",async()=>{const bytes=pdf("Application deadline 2026-09-18 18:00");const row={id:"att-r2",raw_notice_id:"raw-1",source_id:"s",source_run_id:null,parent_attachment_id:null,name:"notice.pdf",url:"https://example.com/disappeared.pdf",content_type:"application/pdf",extension:"pdf",document_role:"PRIMARY",priority:100,fetch_status:"FETCHED",parse_status:"PARSED",content_hash:"abc",r2_key:"attachments/s/raw-1/att-r2/original.pdf",archive_depth:0};const stored=fakeDb(row);let r2Reads=0;const result=await processAttachmentMessage({DB:stored.db,ATTACHMENTS:{get:async()=>{r2Reads++;return{arrayBuffer:async()=>bytes.slice().buffer};},head:async()=>({}),put:async()=>({})}},{attachmentId:row.id,rawNoticeId:row.raw_notice_id,sourceId:"s",url:row.url},async()=>{throw new Error("upstream must not be fetched")},true);assert.equal(result.status,"PARSED");assert.equal(r2Reads,1)});
