import assert from "node:assert/strict";
import test from "node:test";
import { dedupeNotices, makeDedupeKey } from "../lib/collectors/dedupe.ts";
import { runCollection } from "../lib/collectors/run.ts";
import type { Collector, RawNotice, SourceDefinition } from "../lib/collectors/contracts.ts";
import { RssCollector } from "../lib/collectors/rss-collector.ts";
import { SeoulNewsApiCollector } from "../lib/collectors/seoul-news-api-collector.ts";
import { YouthBoardCollector } from "../lib/collectors/web-collector.ts";

const source=(id:string):SourceDefinition=>({id,name:id,method:"WEB",region:"전국",url:`https://example.com/${id}`,implemented:true,health:"GREEN"});
const notice=(id:string):RawNotice=>({sourceId:id,sourceNoticeId:null,title:"청소년 지원사업 공모",url:`https://example.com/${id}/1`,publishedAt:null,rawText:"raw",collectedAt:new Date(0).toISOString(),dedupeKey:makeDedupeKey(id,"청소년 지원사업 공모",`https://example.com/${id}/1`)});
test("one source failure does not stop successful collectors",async()=>{const collectors:Collector[]=[{source:source("a"),collect:async()=>[notice("a")]},{source:source("b"),collect:async()=>{throw new Error("isolated failure")}},{source:source("c"),collect:async()=>[notice("c")]}];const result=await runCollection(collectors);assert.equal(result.status,"PARTIAL");assert.equal(result.sourceRuns.length,3);assert.equal(result.sourceRuns.filter(x=>x.status==="SUCCESS").length,2);assert.equal(result.sourceRuns.find(x=>x.sourceId==="b")?.error,"isolated failure")});
test("dedupe keeps one raw notice for repeated collection",()=>{const one=notice("a");const duplicate={...one};assert.equal(dedupeNotices([one,duplicate]).length,1)});
test("dedupe preserves notice identity in query parameters and ignores tracking",()=>{const first=makeDedupeKey("a","공고","https://example.com/view?id=1&utm_source=test");const same=makeDedupeKey("a","공고","https://example.com/view?utm_source=other&id=1");const second=makeDedupeKey("a","공고","https://example.com/view?id=2");assert.equal(first,same);assert.notEqual(first,second)});
test("RSS collector parses official item fields into the common RawNotice contract",async()=>{const rssSource:{method:"RSS"}&SourceDefinition={...source("rss"),method:"RSS"};const xml=`<rss><channel><item><title><![CDATA[ 청소년 활동 운영기관 모집 공고 ]]></title><pubDate>2026-08-21 10:00:00</pubDate><cn><![CDATA[<p>공고 본문</p>]]></cn><link><![CDATA[https://example.com/#view/42]]></link></item></channel></rss>`;const collector=new RssCollector(rssSource,async()=>new Response(xml,{status:200,headers:{"content-type":"text/xml"}}));const notices=await collector.collect();assert.equal(notices.length,1);assert.equal(notices[0].sourceNoticeId,"42");assert.equal(notices[0].rawText,"공고 본문");assert.equal(collector.lastHttpStatus,200)});
test("API collector requires a key and parses SeoulNewsList rows",async()=>{const apiSource:{method:"API"}&SourceDefinition={...source("api"),method:"API",url:"http://openapi.example"};await assert.rejects(()=>new SeoulNewsApiCollector(apiSource).collect(),/SEOUL_OPEN_API_KEY/);const body={SeoulNewsList:{RESULT:{CODE:"INFO-000",MESSAGE:"정상 처리되었습니다"},row:[{POST_ID:"7",POST_TITLE:"청소년 프로그램 참여기관 모집",POST_CONTENT:"<p>본문</p>",PUBLISH_DATE:"2026-08-21 10:00:00"}]}};const collector=new SeoulNewsApiCollector(apiSource,"issued-key",async()=>Response.json(body));const notices=await collector.collect();assert.equal(notices.length,1);assert.equal(notices[0].sourceNoticeId,"7");assert.equal(notices[0].rawText,"본문")});
test("core youth board collectors keep official detail ids, titles, and dates",async()=>{const cases:[SourceDefinition,string,string,string][]=[
  [{...source("kywa"),url:"https://www.kywa.or.kr/pressinfo/notice_list.jsp"},'<tr><td><a href="../pressinfo/notice_view.jsp?no=36664">2026년 온라인 청소년 정책제안 공모전 안내</a></td><td>관리자</td><td>2026-08-14</td></tr>',"36664","https://www.kywa.or.kr/pressinfo/notice_view.jsp?no=36664"],
  [{...source("ggyouth"),region:"경기",url:"https://ggyouth.or.kr/07_openYard/noticeList.do"},'<tr><td><a href="javascript:;" idx="261618" atchFileId="FILE_1" data-view>경기도 청소년 교류캠프 참가 청소년 모집 안내</a></td><td>2026-08-18</td></tr>',"261618","https://ggyouth.or.kr/07_openYard/noticeView.do?idx=261618&atchFileId=FILE_1"],
  [{...source("ggyouthnet"),region:"경기",url:"https://ggyouthnet.or.kr/bbs/board.php?bo_table=notice_n"},'<tr><td><a href="https://ggyouthnet.or.kr/bbs/board.php?bo_table=notice_n&amp;wr_id=293">2026 경기 리본 프로젝트 모집 안내</a></td><td>2026-07-10</td></tr>',"293","https://ggyouthnet.or.kr/bbs/board.php?bo_table=notice_n&wr_id=293"],
];for(const [definition,html,id,url] of cases){const collector=new YouthBoardCollector(definition,async()=>new Response(html,{status:200,headers:{"content-type":"text/html"}}));const notices=await collector.collect();assert.equal(notices.length,1,definition.id);assert.equal(notices[0].sourceNoticeId,id);assert.equal(notices[0].url,url);assert.ok(notices[0].publishedAt?.startsWith("2026-"));assert.equal(collector.lastHttpStatus,200);}});
