import assert from "node:assert/strict";
import test from "node:test";
import { dedupeNotices, makeDedupeKey } from "../lib/collectors/dedupe.ts";
import { betaCollectors, runCollection } from "../lib/collectors/run.ts";
import type { Collector, RawNotice, SourceDefinition } from "../lib/collectors/contracts.ts";
import { RssCollector } from "../lib/collectors/rss-collector.ts";
import { SeoulNewsApiCollector } from "../lib/collectors/seoul-news-api-collector.ts";
import { YouthBoardCollector } from "../lib/collectors/web-collector.ts";
import { GrantSourceBoardCollector } from "../lib/collectors/grant-source-board-collector.ts";
import { FetchPolicyError, fetchWithPolicy } from "../lib/collectors/fetch-policy.ts";
import { sourceRegistry } from "../lib/collectors/registry.ts";

const source=(id:string):SourceDefinition=>({id,name:id,method:"WEB",region:"전국",url:`https://example.com/${id}`,implemented:true,enabled:true,health:"GREEN"});
const notice=(id:string):RawNotice=>({sourceId:id,sourceNoticeId:null,title:"청소년 지원사업 공모",url:`https://example.com/${id}/1`,publishedAt:null,rawText:"raw",collectedAt:new Date(0).toISOString(),dedupeKey:makeDedupeKey(id,"청소년 지원사업 공모",`https://example.com/${id}/1`)});
test("one source failure does not stop successful collectors",async()=>{const collectors:Collector[]=[{source:source("a"),collect:async()=>[notice("a")]},{source:source("b"),collect:async()=>{throw new Error("isolated failure")}},{source:source("c"),collect:async()=>[]}];const result=await runCollection(collectors);assert.equal(result.status,"PARTIAL");assert.equal(result.sourceRuns.length,3);assert.equal(result.sourceRuns.filter(x=>x.status==="SUCCESS").length,2);assert.equal(result.sourceRuns.find(x=>x.sourceId==="a")?.result,"SUCCESS_WITH_ITEMS");assert.equal(result.sourceRuns.find(x=>x.sourceId==="c")?.result,"SUCCESS_NO_ITEMS");assert.equal(result.sourceRuns.find(x=>x.sourceId==="b")?.result,"FAILED");assert.equal(result.sourceRuns.find(x=>x.sourceId==="b")?.errorCode,"COLLECTOR_ERROR")});
test("source run classifies parser failures",async()=>{const result=await runCollection([{source:source("parser"),collect:async()=>{throw new SyntaxError("invalid JSON response")}}]);assert.equal(result.status,"FAILED");assert.equal(result.sourceRuns[0].result,"FAILED");assert.equal(result.sourceRuns[0].errorCode,"PARSER_ERROR")});
test("beta collectors include only implemented and enabled sources",()=>{const collectors=betaCollectors();const ids=collectors.map(collector=>collector.source.id).sort();assert.deepEqual(ids,["fry","gfgf","gggov","ggyouth","ggyouthnet","kywa","mogef","mpva","sdream","seoul_city"]);const seoulApi=sourceRegistry.find(item=>item.id==="seoul_news_api");assert.equal(seoulApi?.implemented,true);assert.equal(seoulApi?.enabled,false);assert.ok(!ids.includes("seoul_news_api"));assert.ok(sourceRegistry.filter(item=>!item.implemented).every(item=>!item.enabled))});
test("fetch policy returns a successful response without retry",async()=>{let attempts=0;const response=await fetchWithPolicy("https://example.com",{}, {fetcher:async()=>{attempts++;return new Response("ok")},sleep:async()=>{throw new Error("sleep should not run")}});assert.equal(response.status,200);assert.equal(attempts,1)});
test("fetch policy retries 503 once and then succeeds",async()=>{let attempts=0;const delays:number[]=[];const response=await fetchWithPolicy("https://example.com",{}, {fetcher:async()=>{attempts++;return attempts===1?new Response("busy",{status:503}):new Response("ok")},sleep:async delay=>{delays.push(delay)}});assert.equal(response.status,200);assert.equal(attempts,2);assert.deepEqual(delays,[1000])});
test("fetch policy respects bounded Retry-After for 429",async()=>{let attempts=0;const delays:number[]=[];await fetchWithPolicy("https://example.com",{}, {fetcher:async()=>{attempts++;return attempts===1?new Response("slow",{status:429,headers:{"retry-after":"2"}}):new Response("ok")},sleep:async delay=>{delays.push(delay)}});assert.deepEqual(delays,[2000])});
test("fetch policy classifies 403 without retry",async()=>{let attempts=0;await assert.rejects(()=>fetchWithPolicy("https://example.com",{}, {fetcher:async()=>{attempts++;return new Response("blocked",{status:403})},sleep:async()=>{}}),error=>error instanceof FetchPolicyError&&error.code==="ACCESS_BLOCKED"&&error.attempts===1);assert.equal(attempts,1)});
test("fetch policy bounds timeout retries",async()=>{let attempts=0;const fetcher:typeof fetch=async(_input,init)=>{attempts++;return await new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(init.signal?.reason),{once:true}))};await assert.rejects(()=>fetchWithPolicy("https://example.com",{}, {fetcher,timeoutMs:2,maxAttempts:3,sleep:async()=>{}}),error=>error instanceof FetchPolicyError&&error.code==="FETCH_TIMEOUT"&&error.attempts===3);assert.equal(attempts,3)});
test("dedupe keeps one raw notice for repeated collection",()=>{const one=notice("a");const duplicate={...one};assert.equal(dedupeNotices([one,duplicate]).length,1)});
test("dedupe preserves notice identity in query parameters and ignores tracking",()=>{const first=makeDedupeKey("a","공고","https://example.com/view?id=1&utm_source=test");const same=makeDedupeKey("a","공고","https://example.com/view?utm_source=other&id=1");const second=makeDedupeKey("a","공고","https://example.com/view?id=2");assert.equal(first,same);assert.notEqual(first,second)});
test("RSS collector parses official item fields into the common RawNotice contract",async()=>{const rssSource:{method:"RSS"}&SourceDefinition={...source("rss"),method:"RSS"};const xml=`<rss><channel><item><title><![CDATA[ 청소년 활동 운영기관 모집 공고 ]]></title><pubDate>2026-08-21 10:00:00</pubDate><cn><![CDATA[<p>공고 본문</p>]]></cn><link><![CDATA[https://example.com/#view/42]]></link></item></channel></rss>`;const collector=new RssCollector(rssSource,async()=>new Response(xml,{status:200,headers:{"content-type":"text/xml"}}));const notices=await collector.collect();assert.equal(notices.length,1);assert.equal(notices[0].sourceNoticeId,"42");assert.equal(notices[0].rawText,"공고 본문");assert.equal(collector.lastHttpStatus,200)});
test("API collector requires a key and parses SeoulNewsList rows",async()=>{const apiSource:{method:"API"}&SourceDefinition={...source("api"),method:"API",url:"http://openapi.example"};await assert.rejects(()=>new SeoulNewsApiCollector(apiSource).collect(),/SEOUL_OPEN_API_KEY/);const body={SeoulNewsList:{RESULT:{CODE:"INFO-000",MESSAGE:"정상 처리되었습니다"},row:[{POST_ID:"7",POST_TITLE:"청소년 프로그램 참여기관 모집",POST_CONTENT:"<p>본문</p>",PUBLISH_DATE:"2026-08-21 10:00:00"}]}};const collector=new SeoulNewsApiCollector(apiSource,"issued-key",async()=>Response.json(body));const notices=await collector.collect();assert.equal(notices.length,1);assert.equal(notices[0].sourceNoticeId,"7");assert.equal(notices[0].rawText,"본문")});
test("core youth board collectors keep official detail ids, titles, and dates",async()=>{const cases:[SourceDefinition,string,string,string][]=[
  [{...source("kywa"),url:"https://www.kywa.or.kr/pressinfo/notice_list.jsp"},'<tr><td><a href="../pressinfo/notice_view.jsp?no=36664">2026년 온라인 청소년 정책제안 공모전 안내</a></td><td>관리자</td><td>2026-08-14</td></tr>',"36664","https://www.kywa.or.kr/pressinfo/notice_view.jsp?no=36664"],
  [{...source("ggyouth"),region:"경기",url:"https://ggyouth.or.kr/07_openYard/noticeList.do"},'<tr><td><a href="javascript:;" idx="261618" atchFileId="FILE_1" data-view>경기도 청소년 교류캠프 참가 청소년 모집 안내</a></td><td>2026-08-18</td></tr>',"261618","https://ggyouth.or.kr/07_openYard/noticeView.do?idx=261618&atchFileId=FILE_1"],
  [{...source("ggyouthnet"),region:"경기",url:"https://ggyouthnet.or.kr/bbs/board.php?bo_table=notice_n"},'<tr><td><a href="https://ggyouthnet.or.kr/bbs/board.php?bo_table=notice_n&amp;wr_id=293">2026 경기 리본 프로젝트 모집 안내</a></td><td>2026-07-10</td></tr>',"293","https://ggyouthnet.or.kr/bbs/board.php?bo_table=notice_n&wr_id=293"],
];for(const [definition,html,id,url] of cases){const collector=new YouthBoardCollector(definition,async()=>new Response(html,{status:200,headers:{"content-type":"text/html"}}));const notices=await collector.collect();assert.equal(notices.length,1,definition.id);assert.equal(notices[0].sourceNoticeId,id);assert.equal(notices[0].url,url);assert.ok(notices[0].publishedAt?.startsWith("2026-"));assert.equal(collector.lastHttpStatus,200);}});

test("MOGEF board adapter builds canonical detail URLs and ignores navigation links",async()=>{const definition={...source("mogef"),url:"https://www.mogef.go.kr/nw/ntc/nw_ntc_s001.do?mid=news400&div1=16"};const row=`<tr><td class="title"><a href="javascript:void(0);" onclick="javascript:fn_selectView('711259')"><span>2027년 청소년의 달 행사 주관기관 공모</span></a></td><td>2026-08-12 ~ 2026-08-28</td><td>2026-08-12</td></tr>`;const html=`<nav><a href="/sp/fam/sp_fam_f005.do">아이돌봄지원사업</a></nav>${row}${row}`;const fetcher:typeof fetch=async()=>new Response(html,{status:200,headers:{"content-type":"text/html; charset=utf-8"}});const first=await new GrantSourceBoardCollector(definition,fetcher).collect();const second=await new GrantSourceBoardCollector(definition,fetcher).collect();assert.equal(first.length,1);assert.equal(first[0].sourceNoticeId,"711259");assert.equal(first[0].url,"https://www.mogef.go.kr/nw/ntc/nw_ntc_s001d.do?mid=news400&bbtSn=711259");assert.ok(first[0].publishedAt?.startsWith("2026-08-12"));assert.equal(first[0].dedupeKey,second[0].dedupeKey)});

test("FRY adapter finds support calls, canonicalizes uid/gid and removes duplicate links",async()=>{const definition={...source("fry"),url:"https://www.fry.or.kr/board_news01/list.php?tn=board_news01"};const notice=`<tr><td><a href="./view.php?tn=board_news01&amp;uid=1044&amp;gid=1012&amp;cpage=12&amp;spage=11">2026 농어촌청소년 성장 네트워크 지원사업 공모</a></td><td>2026.03.09</td></tr>`;const html=`${notice}${notice}<tr><td><a href="./view.php?tn=board_news01&amp;uid=1066&amp;gid=1034">2026 글로벌기업 탐방활동 사업시행</a></td></tr><tr><td><a href="./view.php?tn=board_news01&amp;uid=1061&amp;gid=1029">성큼성큼 꿈자람 프로젝트 지원사업 심사결과 발표</a></td></tr>`;const fetcher:typeof fetch=async()=>new Response(html,{status:200});const first=await new GrantSourceBoardCollector(definition,fetcher).collect();const second=await new GrantSourceBoardCollector(definition,fetcher).collect();assert.equal(first.length,1);assert.equal(first[0].sourceNoticeId,"1044");assert.equal(first[0].url,"https://www.fry.or.kr/board_news01/view.php?tn=board_news01&uid=1044&gid=1012");assert.ok(first[0].publishedAt?.startsWith("2026-03-09"));assert.equal(first[0].dedupeKey,second[0].dedupeKey)});

test("Samsung Dream adapter narrowly collects the learning-center support call",async()=>{const definition={...source("sdream"),url:"https://www.sdream.or.kr/main"};const html=`<ul><li><a href="#null" onclick="onView('BBS25000000000506387', 'BBSDC01'); return false;"><span class="div1"></span>2026년 배움터 교육지원사업 공모 <span class="date">2025-09-22</span></a></li><li><a href="#null" onclick="onView('BBS26000000000578156', 'BBSDC01'); return false;">2026년 멘토와 함께하는 꿈장학 공모 <span class="date">2026-03-16</span></a></li></ul>`;const fetcher:typeof fetch=async()=>new Response(html,{status:200});const first=await new GrantSourceBoardCollector(definition,fetcher).collect();const second=await new GrantSourceBoardCollector(definition,fetcher).collect();assert.equal(first.length,1);assert.equal(first[0].sourceNoticeId,"BBS25000000000506387");assert.equal(first[0].url,"https://www.sdream.or.kr/w/bbs0103V?BBS_SID=BBS25000000000506387");assert.ok(first[0].publishedAt?.startsWith("2025-09-22"));assert.equal(first[0].dedupeKey,second[0].dedupeKey)});
