import assert from "node:assert/strict";
import test from "node:test";
import { fixtureOpportunities } from "../lib/data/fixtures.ts";
import { toGrantViewModel, toPublicGrantList } from "../lib/domain/grant-view-model.ts";
import { eligibilityPresentation, mayVerifyDeadline, safeValue } from "../lib/domain/verification.ts";
import { Verification } from "../lib/domain/types.ts";
import { emptyExplorerFilters, matchesExplorerFilters, parseExplorerQuery, serializeExplorerQuery } from "../lib/domain/explorer-filter.ts";
import { parseSavedGrantIds, toggleSavedGrantId } from "../lib/domain/saved-grants.ts";

test("deadline context rejects event dates and accepts application deadlines",()=>{assert.equal(mayVerifyDeadline("행사일 2026.09.30"),false);assert.equal(mayVerifyDeadline("신청 마감 2026.09.30"),true);assert.equal(mayVerifyDeadline("사업기간 2026.09.01~09.30"),false)});
test("unverified date never creates status or D-Day",()=>{const row=fixtureOpportunities.find(x=>x.id==="community-safety-2026")!;const view=toGrantViewModel(row,new Date("2026-08-21T09:00:00+09:00"));assert.equal(view.status,"일정 확인 필요");assert.equal(view.dDay,null);assert.equal(view.dateLabel,"확인 필요")});
test("review required eligibility is not presented as eligible",()=>{assert.deepEqual(eligibilityPresentation(Verification.REVIEW_REQUIRED),{label:"검토 필요",tone:"review"})});
test("missing values remain explicit and are never fabricated",()=>{assert.equal(safeValue(null),"확인 필요");assert.equal(safeValue(""),"확인 필요")});
test("verified raw opportunity becomes a safe public view model",()=>{const row=fixtureOpportunities.find(x=>x.id==="kywa-global-2026")!;const view=toGrantViewModel(row,new Date("2026-08-21T09:00:00+09:00"));assert.equal(view.status,"마감임박");assert.equal(view.dDay,"D-9");assert.equal(view.eligibilityLabel,"청소년수련시설 신청 가능");assert.equal(view.selfBurdenLabel,"확인 필요")});
test("manual verification is presented while excluded opportunities stay out of Public",()=>{const row=fixtureOpportunities[0];const manual={...row,deadlineVerification:Verification.MANUAL_CONFIRMED,eligibilityVerification:Verification.MANUAL_CONFIRMED,reviewStatus:"CONFIRMED" as const};const view=toGrantViewModel(manual,new Date("2026-08-21T09:00:00+09:00"));assert.equal(view.eligibilityLabel,"청소년수련시설 신청 가능");assert.notEqual(view.dateLabel,"확인 필요");assert.equal(toPublicGrantList([{...manual,reviewStatus:"EXCLUDED" as const}]).length,0)});
test("eligible region is normalized only from stored data or verified eligibility evidence",()=>{const row=fixtureOpportunities[2];assert.equal(toGrantViewModel(row).eligibleRegion,"경기");assert.equal(toGrantViewModel({...row,eligibilityVerification:Verification.UNKNOWN}).eligibleRegion,"확인 필요");assert.equal(toGrantViewModel({...row,eligibleRegion:"전국",eligibilityVerification:Verification.UNKNOWN}).eligibleRegion,"전국")});
test("Explorer query preserves Korean search and multi-select filters",()=>{const query=serializeExplorerQuery({search:"문화예술",region:"경기",facility:["청소년문화의집","청소년수련관"],category:["문화·예술"],status:["접수중"]});assert.deepEqual(parseExplorerQuery(`?${query}`),{search:"문화예술",region:"경기",facility:["청소년문화의집","청소년수련관"],category:["문화·예술"],status:["접수중"]})});
test("Explorer search and filter groups use AND while nationwide eligibility matches a selected region",()=>{const base=toGrantViewModel({...fixtureOpportunities[0],eligibleRegion:"전국"},new Date("2026-08-04T09:00:00+09:00"));const filters={...emptyExplorerFilters,search:"한국청소년",region:"경기",facility:["청소년수련관"],category:["국제·교류"],status:["접수중"]};assert.equal(matchesExplorerFilters(base,filters),true);assert.equal(matchesExplorerFilters(base,{...filters,search:"없는 공고"}),false);assert.equal(matchesExplorerFilters(base,{...filters,facility:["청소년야영장"]}),false)});
test("saved grant storage survives valid JSON and toggles without duplicates",()=>{assert.deepEqual(parseSavedGrantIds('["a","b",3]'),["a","b"]);assert.deepEqual(parseSavedGrantIds("broken"),[]);assert.deepEqual(toggleSavedGrantId(["a"],"b"),["a","b"]);assert.deepEqual(toggleSavedGrantId(["a","b"],"a"),["b"])});
