import assert from "node:assert/strict";
import test from "node:test";
import type { D1DatabaseLike } from "../lib/cloudflare.ts";
import { finalizeOpportunityVerification, finalReviewStatus } from "../lib/data/opportunity-finalization.ts";
import { ReviewStatus, Verification } from "../lib/domain/types.ts";

test("optional funding and self-burden unknowns do not block PUBLISHED",()=>{assert.equal(finalReviewStatus({deadline_verification:Verification.VERIFIED,eligibility_verification:Verification.VERIFIED,amount_evidence:null,self_burden_evidence:null}),ReviewStatus.PUBLISHED)});
test("missing core eligibility or deadline requires Opportunity review",()=>{assert.equal(finalReviewStatus({deadline_verification:Verification.VERIFIED,eligibility_verification:Verification.UNKNOWN,amount_evidence:null,self_burden_evidence:null}),ReviewStatus.REVIEW_REQUIRED);assert.equal(finalReviewStatus({deadline_verification:Verification.UNKNOWN,eligibility_verification:Verification.VERIFIED,amount_evidence:null,self_burden_evidence:null}),ReviewStatus.REVIEW_REQUIRED)});
test("financial attachment conflicts require review",()=>{assert.equal(finalReviewStatus({deadline_verification:Verification.VERIFIED,eligibility_verification:Verification.VERIFIED,amount_evidence:"[ATTACHMENT CONFLICT] 금액 불일치",self_burden_evidence:null}),ReviewStatus.REVIEW_REQUIRED)});

test("PENDING finalization transitions and notifies only once",async()=>{
  const row={id:"opp-1",title:"지원사업",organization:"기관",deadline:"2026-09-01T18:00:00+09:00",deadline_verification:Verification.VERIFIED,eligibility_verification:Verification.VERIFIED,eligible_region:"전국",amount_evidence:null,self_burden_evidence:null,review_status:ReviewStatus.PENDING,attachment_discovery_status:"COMPLETE",pending_attachments:0};let sends=0;
  const db={prepare(query:string){let values:unknown[]=[];return{bind(...next:unknown[]){values=next;return this;},async first(){return query.startsWith("SELECT o.id")?{...row}:null;},async all(){return{results:[]};},async run(){if(query.startsWith("UPDATE opportunities")&&row.review_status===ReviewStatus.PENDING){row.review_status=String(values[0]) as typeof row.review_status;return{meta:{changes:1}};}return{meta:{changes:0}};}};},async batch(){return[];}} as unknown as D1DatabaseLike;
  const options={notifyNewOpportunity:true,telegram:{environment:"production" as const,siteOrigin:"https://youthgrant.example",botToken:"token",chatId:"chat"},telegramDependencies:{fetcher:async()=>{sends++;return new Response("ok")}}};
  assert.deepEqual(await finalizeOpportunityVerification(db,"raw-1",options),{status:ReviewStatus.PUBLISHED,transitioned:true});assert.deepEqual(await finalizeOpportunityVerification(db,"raw-1",options),{status:ReviewStatus.PUBLISHED,transitioned:false});assert.equal(sends,1);
});

test("PENDING stays internal while discovery or parsing is unfinished",async()=>{for(const state of [{attachment_discovery_status:"PENDING",pending_attachments:0},{attachment_discovery_status:"COMPLETE",pending_attachments:1}]){const row={id:"opp-1",title:"지원사업",organization:"기관",deadline:null,deadline_verification:Verification.UNKNOWN,eligibility_verification:Verification.UNKNOWN,eligible_region:null,amount_evidence:null,self_burden_evidence:null,review_status:ReviewStatus.PENDING,...state};const db={prepare(){return{bind(){return this;},async first(){return row;},async all(){return{results:[]};},async run(){throw new Error("must not finalize");}};},async batch(){return[];}} as unknown as D1DatabaseLike;assert.deepEqual(await finalizeOpportunityVerification(db,"raw-1"),{status:ReviewStatus.PENDING,transitioned:false});}});
