import assert from "node:assert/strict";
import test from "node:test";
import type { D1DatabaseLike } from "../lib/cloudflare.ts";
import { parseReviewMutation } from "../lib/data/review-mutation.ts";
import { reverifyOpportunity, TargetedReverificationError } from "../lib/data/opportunity-reverification.ts";

const valid={reviewStatus:"CONFIRMED",deadline:{decision:"CONFIRMED",value:"2026-09-18T18:00:00+09:00"},eligibility:{decision:"ELIGIBLE",facilityTypes:["청소년문화의집"],note:"원문에서 신청 가능 확인"},amount:{decision:"CONFIRMED",won:20000000,text:"기관당 최대 2,000만원"},selfBurden:{decision:"NONE"}};
test("manual review input preserves explicit operator decisions",()=>{const parsed=parseReviewMutation(valid);assert.equal(parsed.reviewStatus,"CONFIRMED");assert.equal(parsed.deadline.value,valid.deadline.value);assert.deepEqual(parsed.eligibility.facilityTypes,["청소년문화의집"]);assert.equal(parsed.selfBurden.decision,"NONE")});
test("manual review rejects an unconfirmed deadline value",()=>{assert.throws(()=>parseReviewMutation({...valid,deadline:{decision:"CONFIRMED",value:""}}),/신청 마감일/)});

function targetedDb(reviewStatus:string,{stale=true}:{stale?:boolean}={}){
  let claimed=false;let final={review_status:reviewStatus,deadline:"2025-10-14T23:59:00+09:00" as string|null,deadline_verification:"VERIFIED",eligibility_verification:"UNKNOWN",facility_types_json:'["기타 / 확인 필요"]'};const queries:string[]=[];
  const db={prepare(query:string){queries.push(query);return{bind(){return this;},async first(){if(query.includes("FROM opportunities o JOIN opportunity_sources"))return{id:"opp-sdream",review_status:reviewStatus,raw_notice_id:"raw-sdream",source_id:"sdream",source_run_id:"run-sdream",source_notice_id:"1",title:"2026년 배움터 교육지원사업 공모",url:"https://www.sdream.or.kr/w/bbs0103V?id=1",published_at:null,raw_text:"공모 본문",collected_at:"2026-08-25T06:00:00.000Z",dedupe_key:"sdream:1",relevance_status:"IN_SCOPE",attachment_discovery_status:"COMPLETE"};if(query.includes("pending_attachments"))return{id:"opp-sdream",title:"2026년 배움터 교육지원사업 공모",organization:"삼성꿈장학재단",deadline:final.deadline,deadline_verification:final.deadline_verification,eligibility_verification:final.eligibility_verification,eligible_region:null,amount_evidence:null,self_burden_evidence:null,review_status:final.review_status,attachment_discovery_status:"COMPLETE",pending_attachments:0};if(query.startsWith("SELECT COUNT(*) AS count FROM attachments"))return{count:claimed&&final.review_status!=="PUBLISHED"?1:0};if(query.startsWith("SELECT review_status,deadline"))return final;return null;},async all(){return{results:query.includes("SELECT id,url FROM attachments")&&stale?[{id:"att-sdream",url:"https://www.sdream.or.kr/download?fileSid=1"}]:[]};},async run(){if(query.includes("UPDATE attachments SET parse_status='PENDING'")){if(claimed)return{meta:{changes:0}};claimed=true;return{meta:{changes:1}};}return{meta:{changes:1}};}};},async batch(){return[];}} as unknown as D1DatabaseLike;
  return{db,queries,setPublished(){final={review_status:"PUBLISHED",deadline:"2025-11-05T17:00:00+09:00",deadline_verification:"VERIFIED",eligibility_verification:"VERIFIED",facility_types_json:'["청소년 관련 기관·단체"]'};}};
}

test("targeted Samsung stale attachment reverification reaches PUBLISHED without notification",async()=>{const stored=targetedDb("REVIEW_REQUIRED");let calls=0;const result=await reverifyOpportunity({DB:stored.db},"opp-sdream",{async processMessage(_env,message){calls++;assert.equal(message.notifyOnFinalize,false);assert.equal(message.reverify,true);stored.setPublished();return{status:"PARSED" as const,format:"PDF" as const,evidence:2};}});assert.equal(calls,1);assert.equal(result.deadline,"2025-11-05T17:00:00+09:00");assert.equal(result.deadlineVerification,"VERIFIED");assert.equal(result.eligibilityVerification,"VERIFIED");assert.equal(result.reviewStatus,"PUBLISHED");});
test("targeted reverification skips attachments on the latest verification version",async()=>{const stored=targetedDb("REVIEW_REQUIRED",{stale:false});let calls=0;const result=await reverifyOpportunity({DB:stored.db},"opp-sdream",{async processMessage(){calls++;return{status:"PARSED" as const,format:"PDF" as const,evidence:0};}});assert.equal(calls,0);assert.equal(result.processed,0);assert.ok(stored.queries.some(query=>query.includes("verification_version<>?")));});
test("targeted reverification rejects manual and published states",async()=>{for(const status of ["CONFIRMED","DEFERRED","EXCLUDED","PUBLISHED"]){const stored=targetedDb(status);await assert.rejects(()=>reverifyOpportunity({DB:stored.db},"opp-sdream"),error=>error instanceof TargetedReverificationError&&error.status===409);}});
test("concurrent targeted reverification atomically processes one attachment once",async()=>{const stored=targetedDb("REVIEW_REQUIRED");let calls=0;const processMessage=async()=>{calls++;await new Promise(resolve=>setTimeout(resolve,5));stored.setPublished();return{status:"PARSED" as const,format:"PDF" as const,evidence:2};};const results=await Promise.allSettled([reverifyOpportunity({DB:stored.db},"opp-sdream",{processMessage}),reverifyOpportunity({DB:stored.db},"opp-sdream",{processMessage})]);assert.equal(calls,1);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);const rejected=results.find(result=>result.status==="rejected");assert.ok(rejected?.status==="rejected"&&rejected.reason instanceof TargetedReverificationError&&rejected.reason.status===409);});
