import { getLatestCrawlRun, listSourceMonitor } from "../../../lib/data/d1-repository.ts";

export const metadata={title:"Source Monitor · Ops"};
export const dynamic="force-dynamic";

function kst(value:string|null){if(!value)return"—";return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));}

export default async function SourceMonitor(){
  const [sources,lastRun,lastAutomation]=await Promise.all([listSourceMonitor(),getLatestCrawlRun(),getLatestCrawlRun("AUTOMATION")]);const greens=sources.filter(s=>s.health==="GREEN").length;const yellows=sources.filter(s=>s.health==="YELLOW").length;const reds=sources.filter(s=>s.health==="RED").length;
  return <main className="ops-main"><div className="ops-title source-title"><div><h1>Source Monitor</h1><p>{sources.length}개 Source registry · 마지막 {lastRun?.trigger??"실행 없음"} {kst(lastRun?.startedAt??null)} · 최근 AUTOMATION {kst(lastAutomation?.startedAt??null)} {lastAutomation?.status??"—"}</p></div><div className="health-summary"><span className="green">GREEN {greens}</span><span className="yellow">YELLOW {yellows}</span><span className="red">RED {reds}</span></div></div><div className="source-grid">{sources.map(source=><article className="source-card" key={source.id}><header><span className={`health-dot ${source.health.toLowerCase()}`}/><div><h2>{source.name}</h2><p>{source.id} · {source.method} · {source.region}</p></div><span className={`implementation ${source.implemented?"done":"todo"}`}>{source.implemented?"구현":"대기"}</span></header><dl><div><dt>Health</dt><dd>{source.health}</dd></div><div><dt>마지막 실행</dt><dd>{kst(source.lastRunAt)}</dd></div><div><dt>발견 / 신규</dt><dd>{source.found===null?"—":`${source.found} / ${source.itemsNew}`}</dd></div><div><dt>갱신 / 매칭</dt><dd>{source.itemsUpdated===null?"—":`${source.itemsUpdated} / ${source.matched}`}</dd></div><div><dt>결과</dt><dd>{source.result??(source.implemented?"실행 전":"수집기 미구현")}</dd></div><div><dt>HTTP / Parser</dt><dd>{source.httpStatus??"—"} · {source.parserVersion??"—"}</dd></div><div><dt>오류</dt><dd className={source.error?"":"muted"}>{source.error??"없음"}</dd></div></dl></article>)}</div></main>;
}
