import { getLatestCrawlRun, listSourceMonitor } from "../../../lib/data/d1-repository.ts";

export const metadata={title:"Source Monitor · Ops"};
export const dynamic="force-dynamic";

function kst(value:string|null){if(!value)return"—";return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));}

export default async function SourceMonitor(){
  const [sources,lastRun,lastAutomation]=await Promise.all([listSourceMonitor(),getLatestCrawlRun(),getLatestCrawlRun("AUTOMATION")]);const greens=sources.filter(s=>s.operationalHealth==="GREEN").length;const yellows=sources.filter(s=>s.operationalHealth==="YELLOW").length;const reds=sources.filter(s=>s.operationalHealth==="RED").length;
  return <main className="ops-main"><div className="ops-title source-title"><div><h1>Source Monitor</h1><p>{sources.length}개 Source registry · 마지막 {lastRun?.trigger??"실행 없음"} {kst(lastRun?.startedAt??null)} · 최근 AUTOMATION {kst(lastAutomation?.startedAt??null)} {lastAutomation?.status??"—"}</p></div><div className="health-summary"><span className="green">GREEN {greens}</span><span className="yellow">YELLOW {yellows}</span><span className="red">RED {reds}</span></div></div><div className="source-grid">{sources.map(source=>{const state=!source.implemented?{label:"미구현",tone:"todo"}:source.enabled?{label:"활성",tone:"done"}:{label:"일시중지",tone:"paused"};const healthTone=source.operationalHealth==="N/A"?"":source.operationalHealth.toLowerCase();return <article className="source-card" key={source.id}><header><span className={`health-dot ${healthTone}`}/><div><h2>{source.name}</h2><p>{source.id} · {source.method} · {source.region}</p></div><span className={`implementation ${state.tone}`}>{state.label}</span></header><dl><div><dt>Operational Health</dt><dd>{source.operationalHealth}</dd></div><div><dt>마지막 실행</dt><dd>{kst(source.lastRunAt)}</dd></div><div><dt>마지막 성공</dt><dd>{kst(source.lastSuccessAt)}</dd></div><div><dt>연속 실패</dt><dd>{source.enabled?source.consecutiveFailures:"—"}</dd></div><div><dt>발견 / 신규</dt><dd>{source.found===null?"—":`${source.found} / ${source.itemsNew}`}</dd></div><div><dt>갱신 / 매칭</dt><dd>{source.itemsUpdated===null?"—":`${source.itemsUpdated} / ${source.matched}`}</dd></div><div><dt>첨부 탐색</dt><dd>{`대기 ${source.discoveryPending} · 완료 ${source.discoveryComplete} · 미지원 ${source.discoveryUnsupported} · 실패 ${source.discoveryFailed}`}</dd></div><div><dt>첨부 발견 / Fetch</dt><dd>{source.attachmentsDiscovered===null?"—":`${source.attachmentsDiscovered} / ${source.attachmentsFetchSuccess}`}</dd></div><div><dt>Parse / 실패 / OCR</dt><dd>{source.attachmentsParseSuccess===null?"—":`${source.attachmentsParseSuccess} / ${source.attachmentsParseFailed} / ${source.attachmentsOcrRequired}`}</dd></div><div><dt>복구 필드</dt><dd>{source.fieldsRecovered??"—"}</dd></div><div><dt>결과</dt><dd>{source.result??(source.enabled?"실행 전":source.implemented?"일시중지":"수집기 미구현")}</dd></div><div><dt>HTTP / Parser</dt><dd>{source.httpStatus??"—"} · {source.parserVersion??"—"}</dd></div><div><dt>오류 코드</dt><dd className={source.errorCode?"":"muted"}>{source.errorCode??"없음"}</dd></div><div><dt>오류</dt><dd className={source.error?"":"muted"}>{source.error??"없음"}</dd></div></dl></article>;})}</div></main>;
}
