import Link from "next/link";
import { getOpsReviewOverview, listReviewQueue } from "../../../lib/data/d1-repository.ts";

export const metadata={title:"검토대기 · Ops"};
export const dynamic="force-dynamic";

function date(value:string|null){if(!value)return "확인 필요";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?"확인 필요":new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(parsed);}

export default async function ReviewQueue(){
  const [reviews,overview]=await Promise.all([listReviewQueue(),getOpsReviewOverview()]);const quality=overview.quality;
  return <main className="ops-main">
    <section className="quality-panel" aria-labelledby="quality-title"><div className="ops-title"><h1 id="quality-title">Beta Data Quality</h1><p>현재 Public 노출 가능 IN_SCOPE 공고의 검증 상태입니다.</p></div><dl className="quality-grid"><div><dt>Public 대상</dt><dd>{quality.publicTotal}</dd></div><div><dt>검토 필요</dt><dd>{quality.reviewNeeded}</dd></div><div><dt>중복 후보</dt><dd>{quality.duplicateCandidatePairs}</dd></div><div><dt>마감 검증</dt><dd>{quality.deadlineVerified}</dd></div><div><dt>마감 확인 필요</dt><dd>{quality.deadlineUnknown}</dd></div><div><dt>자격 검증</dt><dd>{quality.eligibilityVerified}</dd></div><div><dt>자격 확인 필요</dt><dd>{quality.eligibilityUnknown}</dd></div></dl></section>
    <section className="duplicate-section" aria-labelledby="duplicate-title"><div className="ops-title"><h2 id="duplicate-title">중복 후보 <strong>{overview.candidates.length}</strong>쌍</h2><p>서로 다른 Source의 유사 공고입니다. 자동 병합이나 Public 숨김은 수행하지 않습니다.</p></div>{overview.candidates.length?<div className="duplicate-list">{overview.candidates.slice(0,100).map(candidate=><article className="duplicate-pair" key={`${candidate.left.id}:${candidate.right.id}`}><header><span className={`duplicate-level ${candidate.matchLevel.toLowerCase()}`}>{candidate.matchLevel}</span><strong>{candidate.reason}</strong></header><div className="duplicate-sides">{[candidate.left,candidate.right].map((item,index)=><div key={item.id}><span>공고 {index?"B":"A"}</span><h3>{item.title}</h3><p>{item.sourceName} · {item.organization}</p><dl><div><dt>게시/수집</dt><dd>{date(item.publishedAt??item.collectedAt)}</dd></div><div><dt>마감</dt><dd>{date(item.deadline)}</dd></div></dl><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">원문 확인 ↗</a></div>)}</div><p className="normalized-title">정규화 제목 · {candidate.normalizedTitle}</p></article>)}</div>:<div className="ops-empty"><h3>현재 중복 후보가 없습니다.</h3><p>보수적 기준을 통과한 Cross-Source pair만 여기에 표시됩니다.</p></div>}</section>
    <section aria-labelledby="review-title"><div className="ops-title"><h2 id="review-title">검토대기 공고 <strong>{reviews.length}</strong>건</h2><p>실제 D1에 저장된 자동 추출 결과 중 확정할 수 없는 항목입니다. 확정 전까지 사용자 화면에는 ‘확인 필요’로 노출됩니다.</p></div>{reviews.length?<div className="review-list">{reviews.map(item=><article className="review-row" key={item.id}><div><h3>{item.title}</h3><p>{item.sourceName} · {item.sourceId}</p>{item.attachmentSummary?<p>{item.attachmentSummary}</p>:null}</div><div><span className={`review-flag ${item.tone}`}>{item.flag}</span><p>{item.reason}</p></div><pre>{item.raw}</pre><div className="review-actions"><a href={`/ops/review/${item.id}`}>검토하기</a><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">원문 확인 ↗</a><Link href={`/grants/${item.id}`}>Public 표시 확인</Link></div></article>)}</div>:<div className="ops-empty"><h3>현재 검토대기 공고가 없습니다.</h3><p>Collector가 실행되면 검증이 필요한 공고가 여기에 표시됩니다.</p></div>}</section>
  </main>;
}
