import type { D1DatabaseLike, QueueLike, R2BucketLike, YouthGrantEnv } from "../cloudflare.ts";
import type { AttachmentEvidence, AttachmentQueueMessage, DocumentRole } from "./contracts.ts";
import { classifyDocumentRole } from "./discovery.ts";
import { detectAttachmentFormat, extensionOf } from "./file-type.ts";
import { parseAttachmentBytes } from "./parsers.ts";
import { applyAttachmentEvidence, extractAttachmentEvidence } from "./verification.ts";

const MAX_ATTACHMENT_BYTES=10*1024*1024;
const FINAL_STATUSES=new Set(["PARSED","OCR_REQUIRED","UNSUPPORTED","HWP_PARSER_BLOCKED"]);
type AttachmentRow={id:string;raw_notice_id:string;source_id:string|null;source_run_id:string|null;parent_attachment_id:string|null;name:string;url:string;content_type:string|null;extension:string|null;document_role:DocumentRole;priority:number;fetch_status:string;parse_status:string;content_hash:string|null;r2_key:string|null;archive_depth:number};

export async function attachmentContentHash(bytes:Uint8Array){const digest=await crypto.subtle.digest("SHA-256",bytes.slice().buffer);return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
async function stableId(value:string){return`att_${(await attachmentContentHash(new TextEncoder().encode(value))).slice(0,24)}`;}
function safeSegment(value:string){return value.replace(/[^a-zA-Z0-9._-]+/g,"_").slice(0,100)||"file";}
function dispositionFilename(value:string|null){if(!value)return null;const encoded=value.match(/filename\*=UTF-8''([^;]+)/i)?.[1];if(encoded){try{return decodeURIComponent(encoded);}catch{/**/}}const plain=value.match(/filename="?([^";]+)"?/i)?.[1]?.trim()??null;if(plain?.includes("%")){try{return decodeURIComponent(plain);}catch{/**/}}return plain;}
async function metric(db:D1DatabaseLike,sourceRunId:string|null,column:string,amount=1){if(!sourceRunId)return;const allowed=new Set(["attachments_discovered","attachments_fetch_success","attachments_parse_success","attachments_parse_failed","attachments_ocr_required","fields_recovered","fields_verified_by_attachment"]);if(!allowed.has(column))return;await db.prepare(`UPDATE source_runs SET ${column}=${column}+? WHERE id=?`).bind(amount,sourceRunId).run();}
async function loadBytes(row:AttachmentRow,bucket:R2BucketLike,fetcher:typeof fetch){
  if(row.r2_key&&row.fetch_status==="FETCHED"){const object=await bucket.get(row.r2_key);if(!object)throw new Error("R2_OBJECT_MISSING");return{bytes:new Uint8Array(await object.arrayBuffer()),contentType:row.content_type,filename:row.name};}
  if(row.url.startsWith("r2://")){const key=row.url.slice(5);const object=await bucket.get(key);if(!object)throw new Error("R2_OBJECT_MISSING");return{bytes:new Uint8Array(await object.arrayBuffer()),contentType:row.content_type,filename:row.name};}
  const response=await fetcher(row.url,{headers:{"user-agent":"YouthGrant-Public-Beta/3.0 (+https://youthgrant.seoeum1711.workers.dev)"}});if(!response.ok)throw new Error(`ATTACHMENT_HTTP_${response.status}`);const declared=Number(response.headers.get("content-length")??0);if(declared>MAX_ATTACHMENT_BYTES)throw new Error("ATTACHMENT_TOO_LARGE");const buffer=await response.arrayBuffer();if(buffer.byteLength>MAX_ATTACHMENT_BYTES)throw new Error("ATTACHMENT_TOO_LARGE");return{bytes:new Uint8Array(buffer),contentType:response.headers.get("content-type")??row.content_type,filename:dispositionFilename(response.headers.get("content-disposition"))??row.name};
}
async function registerZipChildren(db:D1DatabaseLike,bucket:R2BucketLike,queue:QueueLike<AttachmentQueueMessage>|undefined,parent:AttachmentRow,children:{filename:string;bytes:Uint8Array}[]){
  let inserted=0;for(const child of children){const childId=await stableId(`${parent.id}:${child.filename}`);const extension=extensionOf(child.filename);const detected=detectAttachmentFormat(child.bytes,child.filename,null);if(detected.format==="UNSUPPORTED")continue;const classified=classifyDocumentRole(child.filename);const key=`attachments/${safeSegment(parent.source_id??"unknown")}/${safeSegment(parent.raw_notice_id)}/${childId}/original.${safeSegment(extension??detected.format.toLowerCase())}`;await bucket.put(key,child.bytes,{httpMetadata:{contentType:detected.detectedMime??undefined},customMetadata:{parentAttachmentId:parent.id}});const hash=await attachmentContentHash(child.bytes);const url=`zip:${parent.url}#${encodeURIComponent(child.filename)}`;const now=new Date().toISOString();const result=await db.prepare(`INSERT OR IGNORE INTO attachments (id,raw_notice_id,source_id,source_run_id,parent_attachment_id,name,url,content_type,extension,size_bytes,document_role,priority,fetch_status,parse_status,content_hash,r2_key,archive_depth,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?, 'FETCHED','PENDING',?,?,?,?)`).bind(childId,parent.raw_notice_id,parent.source_id,parent.source_run_id,parent.id,child.filename,url,detected.detectedMime,extension,child.bytes.byteLength,classified.role,classified.priority,hash,key,parent.archive_depth+1,now).run();if((result.meta?.changes??0)===0)continue;inserted++;if(queue)await queue.send({attachmentId:childId,rawNoticeId:parent.raw_notice_id,sourceId:parent.source_id??"unknown",url:`r2://${key}`});else await db.prepare("UPDATE attachments SET parse_status='QUEUE_BLOCKED',error_code='QUEUE_UNAVAILABLE',error_message='ATTACHMENT_QUEUE binding is unavailable' WHERE id=?").bind(childId).run();}
  await metric(db,parent.source_run_id,"attachments_discovered",inserted);
}
async function fail(db:D1DatabaseLike,row:AttachmentRow,error:unknown){const message=error instanceof Error?error.message:"Attachment processing failed";const code=/^[A-Z0-9_]+$/.test(message)?message:"ATTACHMENT_PROCESSING_FAILED";await db.prepare("UPDATE attachments SET fetch_status=CASE WHEN fetch_status='FETCHED' THEN fetch_status ELSE 'FETCH_FAILED' END,parse_status='PARSE_FAILED',error_code=?,error_message=?,processed_at=? WHERE id=?").bind(code,message,new Date().toISOString(),row.id).run();if(row.parse_status!=="PARSE_FAILED")await metric(db,row.source_run_id,"attachments_parse_failed");}

export async function processAttachmentMessage(env:Pick<YouthGrantEnv,"DB"|"ATTACHMENTS"|"ATTACHMENT_QUEUE">,message:AttachmentQueueMessage,fetcher:typeof fetch=globalThis.fetch.bind(globalThis),force=false){
  const row=await env.DB.prepare("SELECT * FROM attachments WHERE id=?").bind(message.attachmentId).first<AttachmentRow>();if(!row)return{status:"MISSING" as const};if(!force&&row.content_hash&&FINAL_STATUSES.has(row.parse_status))return{status:"SKIPPED" as const};if(!env.ATTACHMENTS)throw new Error("R2_UNAVAILABLE");
  try{const loaded=await loadBytes(row,env.ATTACHMENTS,fetcher);const detected=detectAttachmentFormat(loaded.bytes,loaded.filename,loaded.contentType);if(detected.mismatch)throw new Error("ATTACHMENT_TYPE_MISMATCH");if(detected.format==="UNSUPPORTED")throw new Error("UNSUPPORTED_TYPE");const hash=await attachmentContentHash(loaded.bytes);const extension=extensionOf(loaded.filename)??detected.format.toLowerCase();const classified=classifyDocumentRole(loaded.filename);const effectiveRole=row.document_role==="UNKNOWN"?classified.role:row.document_role;const effectivePriority=row.document_role==="UNKNOWN"?classified.priority:row.priority;const r2Key=row.r2_key??`attachments/${safeSegment(row.source_id??message.sourceId)}/${safeSegment(row.raw_notice_id)}/${row.id}/original.${safeSegment(extension)}`;if(!row.r2_key||!await env.ATTACHMENTS.head(r2Key))await env.ATTACHMENTS.put(r2Key,loaded.bytes,{httpMetadata:{contentType:detected.detectedMime??undefined},customMetadata:{sha256:hash,sourceId:row.source_id??message.sourceId,rawNoticeId:row.raw_notice_id}});await env.DB.prepare("UPDATE attachments SET name=?,extension=?,content_type=?,size_bytes=?,document_role=?,priority=?,fetch_status='FETCHED',content_hash=?,r2_key=?,error_code=NULL,error_message=NULL WHERE id=?").bind(loaded.filename,extension,detected.detectedMime,loaded.bytes.byteLength,effectiveRole,effectivePriority,hash,r2Key,row.id).run();await metric(env.DB,row.source_run_id,"attachments_fetch_success");
    const parsed=await parseAttachmentBytes({attachmentId:row.id,filename:loaded.filename,format:detected.format,role:effectiveRole,bytes:loaded.bytes,archiveDepth:row.archive_depth});let extractionKey:string|null=null;let evidence:AttachmentEvidence[]=[];if(parsed.artifact){extractionKey=`${r2Key}.extracted.json`;if(parsed.status==="PARSED")evidence=extractAttachmentEvidence(parsed.artifact);await env.ATTACHMENTS.put(extractionKey,JSON.stringify(parsed.artifact),{httpMetadata:{contentType:"application/json"},customMetadata:{attachmentId:row.id,parser:parsed.parseMethod}});}await env.DB.prepare("UPDATE attachments SET parse_status=?,parse_method=?,extraction_r2_key=?,evidence_json=?,text_extracted=?,error_code=?,error_message=?,processed_at=? WHERE id=?").bind(parsed.status,parsed.parseMethod,extractionKey,JSON.stringify(evidence),parsed.artifact?.blocks.length?1:0,parsed.errorCode??null,parsed.errorMessage??null,new Date().toISOString(),row.id).run();
    if(parsed.children?.length)await registerZipChildren(env.DB,env.ATTACHMENTS,env.ATTACHMENT_QUEUE,{...row,name:loaded.filename,r2_key:r2Key},parsed.children);if(parsed.status==="PARSED")await metric(env.DB,row.source_run_id,"attachments_parse_success");else if(parsed.status==="OCR_REQUIRED")await metric(env.DB,row.source_run_id,"attachments_ocr_required");else await metric(env.DB,row.source_run_id,"attachments_parse_failed");if(evidence.length){const verification=await applyAttachmentEvidence(env.DB,row.raw_notice_id,evidence);await metric(env.DB,row.source_run_id,"fields_recovered",verification.recovered);await metric(env.DB,row.source_run_id,"fields_verified_by_attachment",verification.verified);}return{status:parsed.status,format:detected.format,evidence:evidence.length};
  }catch(error){await fail(env.DB,row,error);throw error;}
}

export async function reprocessAttachment(env:Pick<YouthGrantEnv,"DB"|"ATTACHMENTS"|"ATTACHMENT_QUEUE">,attachmentId:string){const row=await env.DB.prepare("SELECT id,raw_notice_id,source_id,url FROM attachments WHERE id=?").bind(attachmentId).first<{id:string;raw_notice_id:string;source_id:string|null;url:string}>();if(!row)return false;await env.DB.prepare("UPDATE attachments SET parse_status='PENDING',error_code=NULL,error_message=NULL,processed_at=NULL WHERE id=?").bind(attachmentId).run();await processAttachmentMessage(env,{attachmentId:row.id,rawNoticeId:row.raw_notice_id,sourceId:row.source_id??"unknown",url:row.url},globalThis.fetch.bind(globalThis),true);return true;}
