import type { D1DatabaseLike } from "../cloudflare.ts";
import { ReviewStatus, Verification } from "../domain/types.ts";
import type { AttachmentEvidence, ExtractionArtifact } from "./contracts.ts";

const DEADLINE_CONTEXT=/(신청\s*기간|접수\s*기간|신청\s*마감|접수\s*마감|제출\s*기한)/g;
const ELIGIBILITY_CONTEXT=/(지원\s*대상|신청\s*대상|신청\s*자격|응모\s*대상|참여\s*대상)/;
const FACILITY=/(청소년수련관|청소년문화의집|청소년수련시설|청소년시설|청소년기관|청소년단체|청소년\s*동아리|댄스동아리|동아리)/g;

function dateCandidates(text:string){const values:{year:number;month:number;day:number;hour:number;minute:number}[]=[];let year:number|null=null;for(const match of text.matchAll(/(?:(20\d{2})\s*(?:년|[.\-/]))?\s*(\d{1,2})\s*(?:월|[.\-/])\s*(\d{1,2})\s*일?(?:\s*\([^)]*\))?\s*(?:(\d{1,2})\s*(?::|시)\s*(\d{1,2})?\s*분?)?/g)){if(match[1])year=Number(match[1]);if(!year)continue;const hour=match[4]?Number(match[4]):/까지/.test(text.slice(match.index??0,(match.index??0)+60))?23:23;const minute=match[5]?Number(match[5]):match[4]?0:59;values.push({year,month:Number(match[2]),day:Number(match[3]),hour,minute});}return values;}
function deadlineEvidence(artifact:ExtractionArtifact):AttachmentEvidence|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){for(const context of block.text.matchAll(DEADLINE_CONTEXT)){const start=context.index??0;const snippet=block.text.slice(start,start+260);if(/^(?:행사일|사업기간|교육기간|발표일|설명회)/.test(snippet))continue;const dates=dateCandidates(snippet);const chosen=dates.at(-1);if(!chosen)continue;const value=`${chosen.year}-${String(chosen.month).padStart(2,"0")}-${String(chosen.day).padStart(2,"0")}T${String(chosen.hour).padStart(2,"0")}:${String(chosen.minute).padStart(2,"0")}:00+09:00`;return{field:"deadline",value,evidenceText:snippet.trim(),attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}}return null;}
function eligibilityEvidence(artifact:ExtractionArtifact):AttachmentEvidence|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){const context=ELIGIBILITY_CONTEXT.exec(block.text);if(!context)continue;const snippet=block.text.slice(context.index,context.index+320);const facilities=[...new Set([...snippet.matchAll(FACILITY)].map(match=>match[0].replace(/\s+/g,"")))];if(!facilities.length)continue;return{field:"eligibility",value:facilities,evidenceText:snippet.trim(),attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}return null;}
function amountEvidence(artifact:ExtractionArtifact):AttachmentEvidence|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){const match=block.text.match(/((?:기관|시설|단체|동아리|팀)당[^.\n]{0,100}?(?:최대\s*)?([0-9][0-9,]*(?:\.\d+)?)\s*(억원|천만원|만원|원))/);if(!match)continue;const amount=Number(match[2].replace(/,/g,""))*(match[3]==="억원"?100_000_000:match[3]==="천만원"?10_000_000:match[3]==="만원"?10_000:1);if(!Number.isFinite(amount)||amount<=0)continue;return{field:"amount",value:Math.round(amount),evidenceText:match[1],attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}return null;}
function selfBurdenEvidence(artifact:ExtractionArtifact):AttachmentEvidence|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){const match=block.text.match(/(자부담[^.\n]{0,80}?(없음|0\s*%|[0-9]+(?:\.[0-9]+)?\s*%))/);if(!match)continue;const value=/없음|0\s*%/.test(match[2])?"없음":match[2].replace(/\s+/g,"");return{field:"self_burden",value,evidenceText:match[1],attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}return null;}
export function extractAttachmentEvidence(artifact:ExtractionArtifact){return[deadlineEvidence(artifact),eligibilityEvidence(artifact),amountEvidence(artifact),selfBurdenEvidence(artifact)].filter((item):item is AttachmentEvidence=>Boolean(item));}

function verified(value:string){return value===Verification.VERIFIED||value===Verification.MANUAL_CONFIRMED;}
function sameDeadline(a:string,b:string){return Math.abs(new Date(a).getTime()-new Date(b).getTime())<60_000;}
function eligibleRegion(text:string){if(/전국/.test(text))return"전국";if(/서울(?:시|특별시)?\s*(?:소재|거주|지역)/.test(text))return"서울";if(/경기(?:도)?\s*(?:소재|거주|지역)/.test(text))return"경기";return null;}

export async function applyAttachmentEvidence(db:D1DatabaseLike,rawNoticeId:string,evidence:AttachmentEvidence[]){
  const row=await db.prepare(`SELECT o.id,o.deadline,o.deadline_verification,o.deadline_evidence,o.eligibility_verification,o.eligibility_evidence,o.facility_types_json,o.amount_won,o.amount_text,o.self_burden,o.review_status FROM opportunities o JOIN opportunity_sources os ON os.opportunity_id=o.id WHERE os.raw_notice_id=? LIMIT 1`).bind(rawNoticeId).first<{id:string;deadline:string|null;deadline_verification:string;deadline_evidence:string|null;eligibility_verification:string;eligibility_evidence:string|null;facility_types_json:string;amount_won:number|null;amount_text:string|null;self_burden:string|null;review_status:string}>();if(!row)return{recovered:0,verified:0,conflict:false};
  let deadline=row.deadline;let deadlineVerification=row.deadline_verification;let deadlineEvidence=row.deadline_evidence;let deadlineLocation:string|null=null;let deadlineAttachment:string|null=null;let eligibilityVerification=row.eligibility_verification;let eligibilityEvidence=row.eligibility_evidence;let eligibilityLocation:string|null=null;let eligibilityAttachment:string|null=null;let facilities:string[]=JSON.parse(row.facility_types_json||"[]");let amountWon=row.amount_won;let amountText=row.amount_text;let amountEvidenceText:string|null=null;let amountAttachment:string|null=null;let selfBurden=row.self_burden;let selfBurdenEvidenceText:string|null=null;let selfBurdenAttachment:string|null=null;let region:string|null=null;let recovered=0;let attachmentVerified=0;let conflict=false;
  for(const item of evidence){if(item.field==="deadline"&&typeof item.value==="string"){if(deadline&&verified(deadlineVerification)&&!sameDeadline(deadline,item.value)){conflict=true;deadlineVerification=Verification.REVIEW_REQUIRED;deadlineEvidence=`${deadlineEvidence??"BODY deadline"}\n[ATTACHMENT CONFLICT] ${item.evidenceText}`;}else if(!verified(deadlineVerification)){deadline=item.value;deadlineVerification=Verification.VERIFIED;deadlineEvidence=item.evidenceText;deadlineLocation=`${item.filename} · ${item.location}`;deadlineAttachment=item.attachmentId;recovered++;attachmentVerified++;}}
    if(item.field==="eligibility"&&Array.isArray(item.value)){const current=facilities.filter(value=>!value.includes("확인 필요"));if(verified(eligibilityVerification)&&current.length&&item.value.some(value=>!current.includes(value))){conflict=true;eligibilityVerification=Verification.REVIEW_REQUIRED;eligibilityEvidence=`${eligibilityEvidence??"BODY eligibility"}\n[ATTACHMENT CONFLICT] ${item.evidenceText}`;}else if(!verified(eligibilityVerification)){facilities=item.value;eligibilityVerification=Verification.VERIFIED;eligibilityEvidence=item.evidenceText;eligibilityLocation=`${item.filename} · ${item.location}`;eligibilityAttachment=item.attachmentId;region=eligibleRegion(item.evidenceText);recovered++;attachmentVerified++;}}
    if(item.field==="amount"&&typeof item.value==="number"){if(amountWon!==null&&amountWon!==item.value)conflict=true;else if(amountWon===null){amountWon=item.value;amountText=item.evidenceText;amountEvidenceText=item.evidenceText;amountAttachment=item.attachmentId;recovered++;attachmentVerified++;}}
    if(item.field==="self_burden"&&typeof item.value==="string"){if(selfBurden&&selfBurden!==item.value)conflict=true;else if(!selfBurden){selfBurden=item.value;selfBurdenEvidenceText=item.evidenceText;selfBurdenAttachment=item.attachmentId;recovered++;attachmentVerified++;}}}
  const complete=verified(deadlineVerification)&&verified(eligibilityVerification)&&!conflict;const preserve=row.review_status===ReviewStatus.CONFIRMED||row.review_status===ReviewStatus.EXCLUDED;const reviewStatus=conflict?ReviewStatus.REVIEW_REQUIRED:preserve?row.review_status:complete?ReviewStatus.PUBLISHED:ReviewStatus.REVIEW_REQUIRED;const now=new Date().toISOString();
  await db.prepare(`UPDATE opportunities SET deadline=?,deadline_verification=?,deadline_evidence=?,deadline_evidence_location=COALESCE(?,deadline_evidence_location),deadline_evidence_source_type=CASE WHEN ? IS NULL THEN deadline_evidence_source_type ELSE 'ATTACHMENT' END,deadline_evidence_attachment_id=COALESCE(?,deadline_evidence_attachment_id),eligibility_verification=?,eligibility_evidence=?,eligibility_evidence_location=COALESCE(?,eligibility_evidence_location),eligibility_evidence_source_type=CASE WHEN ? IS NULL THEN eligibility_evidence_source_type ELSE 'ATTACHMENT' END,eligibility_evidence_attachment_id=COALESCE(?,eligibility_evidence_attachment_id),facility_types_json=?,eligible_region=COALESCE(?,eligible_region),amount_won=?,amount_text=?,amount_evidence=COALESCE(?,amount_evidence),amount_evidence_source_type=CASE WHEN ? IS NULL THEN amount_evidence_source_type ELSE 'ATTACHMENT' END,amount_evidence_attachment_id=COALESCE(?,amount_evidence_attachment_id),self_burden=?,self_burden_evidence=COALESCE(?,self_burden_evidence),self_burden_evidence_source_type=CASE WHEN ? IS NULL THEN self_burden_evidence_source_type ELSE 'ATTACHMENT' END,self_burden_evidence_attachment_id=COALESCE(?,self_burden_evidence_attachment_id),review_status=?,updated_at=? WHERE id=?`).bind(deadline,deadlineVerification,deadlineEvidence,deadlineLocation,deadlineAttachment,deadlineAttachment,eligibilityVerification,eligibilityEvidence,eligibilityLocation,eligibilityAttachment,eligibilityAttachment,JSON.stringify(facilities),region,amountWon,amountText,amountEvidenceText,amountAttachment,amountAttachment,selfBurden,selfBurdenEvidenceText,selfBurdenAttachment,selfBurdenAttachment,reviewStatus,now,row.id).run();return{recovered,verified:attachmentVerified,conflict};
}
