import type { D1DatabaseLike } from "../cloudflare.ts";
import { DeadlineMode, ReviewStatus, Verification } from "../domain/types.ts";
import type { AttachmentEvidence, ExtractionArtifact } from "./contracts.ts";

export const CURRENT_VERIFICATION_VERSION="verification-v3";

type AttachmentEvidenceWithoutUrl=Omit<AttachmentEvidence,"originalUrl">;

const DEADLINE_CONTEXT=/(신청\s*기간|접수\s*기간|공모\s*기간|모집\s*기간|신청\s*마감|접수\s*마감|제출\s*기한|신청\s*기한|신청\s*(?=[:：])|접수\s*(?=[:：]))/g;
const DEADLINE_RANGE_CONTEXT=/(신청\s*기간|접수\s*기간|공모\s*기간|모집\s*기간|신청\s*(?=[:：])|접수\s*(?=[:：]))/;
const NON_DEADLINE_SECTION=/(사업\s*설명회|설명회|오리엔테이션|행사일|교육일|선정\s*발표일?|결과\s*발표일?|사업\s*기간|운영\s*기간|활동\s*기간)/;
const ELIGIBILITY_CONTEXT=/(지원\s*대상|신청\s*대상|신청\s*자격|지원\s*자격|응모\s*대상|참여\s*대상)/;
const ELIGIBLE_APPLICANT=/(청소년수련관|청소년문화의집|청소년수련시설|청소년시설|청소년기관|청소년단체|비영리\s*(?:기관|단체)|기관\s*(?:[·ㆍ/]\s*단체|및\s*단체|\(단체\))|사회복지\s*(?:기관|시설)|학교|센터|시설|청소년\s*동아리|댄스동아리|동아리)/g;

function dateCandidates(text:string){const values:{year:number;month:number;day:number;hour:number;minute:number}[]=[];let year:number|null=null;for(const match of text.matchAll(/(?:(20\d{2})\s*(?:년|[.\-/]))?\s*(\d{1,2})\s*(?:월|[.\-/])\s*(\d{1,2})\s*\.?\s*일?(?:\s*\([^)]*\))?\s*(?:(\d{1,2})\s*(?::|시)\s*(\d{1,2})?\s*분?)?/g)){if(match[1])year=Number(match[1]);if(!year)continue;const month=Number(match[2]);const day=Number(match[3]);const hour=match[4]?Number(match[4]):23;const minute=match[5]?Number(match[5]):match[4]?0:59;if(month<1||month>12||day<1||day>31||hour<0||hour>23||minute<0||minute>59)continue;values.push({year,month,day,hour,minute});}return values;}
function isoDate(value:{year:number;month:number;day:number;hour:number;minute:number},start=false){return`${value.year}-${String(value.month).padStart(2,"0")}-${String(value.day).padStart(2,"0")}T${start?"00":String(value.hour).padStart(2,"0")}:${start?"00":String(value.minute).padStart(2,"0")}:00+09:00`;}
function openEndedPhrase(snippet:string){
  if(/사업비\s*소진\s*시\s*까지/.test(snippet))return"사업비 소진 시까지";
  if(/예산\s*소진\s*시\s*까지/.test(snippet))return"예산 소진 시까지";
  if(/정원\s*마감\s*시\s*까지/.test(snippet))return"정원 마감 시까지";
  if(/모집\s*완료\s*시\s*까지/.test(snippet))return"모집완료 시까지";
  if(/선착순\s*마감/.test(snippet))return"선착순 마감";
  if(/선착순\s*\d+\s*개\s*기관\s*모집/.test(snippet))return"선착순 마감";
  return null;
}
function deadlineEvidence(artifact:ExtractionArtifact):AttachmentEvidenceWithoutUrl|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){for(const context of block.text.matchAll(DEADLINE_CONTEXT)){const start=context.index??0;const candidate=block.text.slice(start,start+260);const excluded=candidate.slice(context[0].length).search(NON_DEADLINE_SECTION);const snippet=(excluded>=0?candidate.slice(0,context[0].length+excluded):candidate).trim();const dates=dateCandidates(snippet);const range=DEADLINE_RANGE_CONTEXT.test(context[0]);const openEnded=openEndedPhrase(snippet);if(openEnded){return{field:"deadline",value:null,deadlineMode:DeadlineMode.OPEN_ENDED,applicationStart:dates[0]?isoDate(dates[0],true):null,evidenceText:openEnded,attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}const chosen=range&&dates.length>=2?dates[1]:dates[0];if(!chosen)continue;const statedClose=snippet.match(/(?:마감일|마감시간|소인분)[^0-9]{0,20}(\d{1,2})\s*:\s*(\d{2})\s*까지/);if(statedClose){const hour=Number(statedClose[1]);const minute=Number(statedClose[2]);if(hour<=23&&minute<=59){chosen.hour=hour;chosen.minute=minute;}}return{field:"deadline",value:isoDate(chosen),deadlineMode:DeadlineMode.FIXED_DATE,applicationStart:range&&dates.length>=2?isoDate(dates[0],true):null,evidenceText:snippet,attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}}return null;}
function applicantType(value:string){const compact=value.replace(/\s+/g,"");if(/^청소년/.test(compact)||/동아리/.test(compact))return compact;if(/비영리|기관|단체|사회복지/.test(compact))return"청소년 관련 기관·단체";return"기타";}
function eligibilityEvidence(artifact:ExtractionArtifact):AttachmentEvidenceWithoutUrl|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){const context=ELIGIBILITY_CONTEXT.exec(block.text);if(!context)continue;const snippet=block.text.slice(context.index,context.index+320);const facilities=[...new Set([...snippet.matchAll(ELIGIBLE_APPLICANT)].map(match=>applicantType(match[0])))];if(!facilities.length)continue;return{field:"eligibility",value:facilities,evidenceText:snippet.trim(),attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}return null;}
function amountEvidence(artifact:ExtractionArtifact):AttachmentEvidenceWithoutUrl|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){const match=block.text.match(/((?:기관|시설|단체|동아리|팀)당[^.\n]{0,100}?(?:최대\s*)?([0-9][0-9,]*(?:\.\d+)?)\s*(억원|천만원|만원|원))/);if(!match)continue;const amount=Number(match[2].replace(/,/g,""))*(match[3]==="억원"?100_000_000:match[3]==="천만원"?10_000_000:match[3]==="만원"?10_000:1);if(!Number.isFinite(amount)||amount<=0)continue;return{field:"amount",value:Math.round(amount),evidenceText:match[1],attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}return null;}
function selfBurdenEvidence(artifact:ExtractionArtifact):AttachmentEvidenceWithoutUrl|null{if(artifact.role==="FORM"||artifact.role==="MEDIA")return null;for(const block of artifact.blocks){const match=block.text.match(/(자부담[^.\n]{0,80}?(없음|0\s*%|[0-9]+(?:\.[0-9]+)?\s*%))/);if(!match)continue;const value=/없음|0\s*%/.test(match[2])?"없음":match[2].replace(/\s+/g,"");return{field:"self_burden",value,evidenceText:match[1],attachmentId:artifact.attachmentId,filename:artifact.filename,location:block.location,sourceType:"ATTACHMENT"};}return null;}
export function extractAttachmentEvidence(artifact:ExtractionArtifact,originalUrl:string){return[deadlineEvidence(artifact),eligibilityEvidence(artifact),amountEvidence(artifact),selfBurdenEvidence(artifact)].filter((item):item is AttachmentEvidenceWithoutUrl=>Boolean(item)).map(item=>({...item,originalUrl}));}

function verified(value:string){return value===Verification.VERIFIED||value===Verification.MANUAL_CONFIRMED;}
function verifiedDeadlineState(mode:string,deadline:string|null,verification:string){return verified(verification)&&(mode===DeadlineMode.OPEN_ENDED||(mode===DeadlineMode.FIXED_DATE&&Boolean(deadline)));}
function sameDeadline(a:string,b:string){return Math.abs(new Date(a).getTime()-new Date(b).getTime())<60_000;}
function sameCalendarDay(a:string,b:string){return a.slice(0,10)===b.slice(0,10);}
function hasExplicitTime(evidence:string|null){return Boolean(evidence&&/\b(?:[01]?\d|2[0-3])\s*:\s*[0-5]\d\b/.test(evidence));}
function eligibleRegion(text:string){if(/전국/.test(text))return"전국";if(/서울(?:시|특별시)?\s*(?:소재|거주|지역)/.test(text))return"서울";if(/경기(?:도)?\s*(?:소재|거주|지역)/.test(text))return"경기";return null;}

export async function applyAttachmentEvidence(db:D1DatabaseLike,rawNoticeId:string,evidence:AttachmentEvidence[]){
  const row=await db.prepare(`SELECT o.id,o.application_start,o.deadline,o.deadline_mode,o.deadline_verification,o.deadline_evidence,o.deadline_evidence_attachment_id,o.eligibility_verification,o.eligibility_evidence,o.facility_types_json,o.amount_won,o.amount_text,o.amount_evidence,o.self_burden,o.self_burden_evidence,o.review_status FROM opportunities o JOIN opportunity_sources os ON os.opportunity_id=o.id WHERE os.raw_notice_id=? LIMIT 1`).bind(rawNoticeId).first<{id:string;application_start:string|null;deadline:string|null;deadline_mode:string;deadline_verification:string;deadline_evidence:string|null;deadline_evidence_attachment_id:string|null;eligibility_verification:string;eligibility_evidence:string|null;facility_types_json:string;amount_won:number|null;amount_text:string|null;amount_evidence:string|null;self_burden:string|null;self_burden_evidence:string|null;review_status:string}>();if(!row)return{recovered:0,verified:0,conflict:false};
  if(row.review_status===ReviewStatus.CONFIRMED||row.review_status===ReviewStatus.DEFERRED||row.review_status===ReviewStatus.EXCLUDED)return{recovered:0,verified:0,conflict:false};
  let applicationStart=row.application_start;let deadline=row.deadline;let deadlineMode=row.deadline_mode??(deadline?DeadlineMode.FIXED_DATE:DeadlineMode.UNKNOWN);let deadlineVerification=row.deadline_verification;let deadlineEvidence=row.deadline_evidence;let deadlineLocation:string|null=null;let deadlineAttachment:string|null=null;let eligibilityVerification=row.eligibility_verification;let eligibilityEvidence=row.eligibility_evidence;let eligibilityLocation:string|null=null;let eligibilityAttachment:string|null=null;let facilities:string[]=JSON.parse(row.facility_types_json||"[]");let amountWon=row.amount_won;let amountText=row.amount_text;let amountEvidenceText:string|null=null;let amountAttachment:string|null=null;let selfBurden=row.self_burden;let selfBurdenEvidenceText:string|null=null;let selfBurdenAttachment:string|null=null;let region:string|null=null;let recovered=0;let attachmentVerified=0;let conflict=false;
  for(const item of evidence){if(item.field==="deadline"){const itemMode=item.deadlineMode??(typeof item.value==="string"?DeadlineMode.FIXED_DATE:DeadlineMode.UNKNOWN);const itemDeadline=typeof item.value==="string"?item.value:null;const sameAttachment=deadlineVerification===Verification.VERIFIED&&row.deadline_evidence_attachment_id===item.attachmentId;if(sameAttachment){applicationStart=item.applicationStart??applicationStart;deadline=itemDeadline;deadlineMode=itemMode;deadlineVerification=Verification.VERIFIED;deadlineEvidence=item.evidenceText;deadlineLocation=`${item.filename} · ${item.location}`;deadlineAttachment=item.attachmentId;recovered++;attachmentVerified++;}else if(verifiedDeadlineState(deadlineMode,deadline,deadlineVerification)){if(deadlineMode!==itemMode){conflict=true;deadlineVerification=Verification.REVIEW_REQUIRED;deadlineEvidence=`${deadlineEvidence??"BODY deadline"}\n[ATTACHMENT CONFLICT] ${item.evidenceText}`;}else if(itemMode===DeadlineMode.FIXED_DATE&&deadline&&itemDeadline&&!sameDeadline(deadline,itemDeadline)){if(sameCalendarDay(deadline,itemDeadline)&&!hasExplicitTime(deadlineEvidence)&&hasExplicitTime(item.evidenceText)){deadline=itemDeadline;deadlineEvidence=item.evidenceText;deadlineLocation=`${item.filename} · ${item.location}`;deadlineAttachment=item.attachmentId;}else if(!(sameCalendarDay(deadline,itemDeadline)&&hasExplicitTime(deadlineEvidence)&&!hasExplicitTime(item.evidenceText))){conflict=true;deadlineVerification=Verification.REVIEW_REQUIRED;deadlineEvidence=`${deadlineEvidence??"BODY deadline"}\n[ATTACHMENT CONFLICT] ${item.evidenceText}`;}}}else{applicationStart=item.applicationStart??applicationStart;deadline=itemDeadline;deadlineMode=itemMode;deadlineVerification=Verification.VERIFIED;deadlineEvidence=item.evidenceText;deadlineLocation=`${item.filename} · ${item.location}`;deadlineAttachment=item.attachmentId;recovered++;attachmentVerified++;}}
    if(item.field==="eligibility"&&Array.isArray(item.value)){const current=facilities.filter(value=>!value.includes("확인 필요"));if(verified(eligibilityVerification)&&current.length&&item.value.some(value=>!current.includes(value))){conflict=true;eligibilityVerification=Verification.REVIEW_REQUIRED;eligibilityEvidence=`${eligibilityEvidence??"BODY eligibility"}\n[ATTACHMENT CONFLICT] ${item.evidenceText}`;}else if(!verified(eligibilityVerification)){facilities=item.value;eligibilityVerification=Verification.VERIFIED;eligibilityEvidence=item.evidenceText;eligibilityLocation=`${item.filename} · ${item.location}`;eligibilityAttachment=item.attachmentId;region=eligibleRegion(item.evidenceText);recovered++;attachmentVerified++;}}
    if(item.field==="amount"&&typeof item.value==="number"){if(amountWon!==null&&amountWon!==item.value){conflict=true;amountEvidenceText=`${row.amount_evidence??"기존 지원금 근거"}\n[ATTACHMENT CONFLICT] ${item.evidenceText}`;amountAttachment=item.attachmentId;}else if(amountWon===null){amountWon=item.value;amountText=item.evidenceText;amountEvidenceText=item.evidenceText;amountAttachment=item.attachmentId;recovered++;attachmentVerified++;}}
    if(item.field==="self_burden"&&typeof item.value==="string"){if(selfBurden&&selfBurden!==item.value){conflict=true;selfBurdenEvidenceText=`${row.self_burden_evidence??"기존 자부담 근거"}\n[ATTACHMENT CONFLICT] ${item.evidenceText}`;selfBurdenAttachment=item.attachmentId;}else if(!selfBurden){selfBurden=item.value;selfBurdenEvidenceText=item.evidenceText;selfBurdenAttachment=item.attachmentId;recovered++;attachmentVerified++;}}}
  const complete=verifiedDeadlineState(deadlineMode,deadline,deadlineVerification)&&verified(eligibilityVerification)&&!conflict;const reviewStatus=row.review_status===ReviewStatus.PENDING?ReviewStatus.PENDING:conflict?ReviewStatus.REVIEW_REQUIRED:complete?ReviewStatus.PUBLISHED:ReviewStatus.REVIEW_REQUIRED;const now=new Date().toISOString();
  await db.prepare(`UPDATE opportunities SET application_start=?,deadline=?,deadline_mode=?,deadline_verification=?,deadline_evidence=?,deadline_evidence_location=COALESCE(?,deadline_evidence_location),deadline_evidence_source_type=CASE WHEN ? IS NULL THEN deadline_evidence_source_type ELSE 'ATTACHMENT' END,deadline_evidence_attachment_id=COALESCE(?,deadline_evidence_attachment_id),eligibility_verification=?,eligibility_evidence=?,eligibility_evidence_location=COALESCE(?,eligibility_evidence_location),eligibility_evidence_source_type=CASE WHEN ? IS NULL THEN eligibility_evidence_source_type ELSE 'ATTACHMENT' END,eligibility_evidence_attachment_id=COALESCE(?,eligibility_evidence_attachment_id),facility_types_json=?,eligible_region=COALESCE(?,eligible_region),amount_won=?,amount_text=?,amount_evidence=COALESCE(?,amount_evidence),amount_evidence_source_type=CASE WHEN ? IS NULL THEN amount_evidence_source_type ELSE 'ATTACHMENT' END,amount_evidence_attachment_id=COALESCE(?,amount_evidence_attachment_id),self_burden=?,self_burden_evidence=COALESCE(?,self_burden_evidence),self_burden_evidence_source_type=CASE WHEN ? IS NULL THEN self_burden_evidence_source_type ELSE 'ATTACHMENT' END,self_burden_evidence_attachment_id=COALESCE(?,self_burden_evidence_attachment_id),review_status=?,updated_at=? WHERE id=?`).bind(applicationStart,deadline,deadlineMode,deadlineVerification,deadlineEvidence,deadlineLocation,deadlineAttachment,deadlineAttachment,eligibilityVerification,eligibilityEvidence,eligibilityLocation,eligibilityAttachment,eligibilityAttachment,JSON.stringify(facilities),region,amountWon,amountText,amountEvidenceText,amountAttachment,amountAttachment,selfBurden,selfBurdenEvidenceText,selfBurdenAttachment,selfBurdenAttachment,reviewStatus,now,row.id).run();return{recovered,verified:attachmentVerified,conflict};
}
