import { index, integer, primaryKey, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const sources=sqliteTable("sources",{id:text("id").primaryKey(),name:text("name").notNull(),method:text("method",{enum:["WEB","RSS","API","OPEN_DATA"]}).notNull(),region:text("region").notNull(),url:text("url").notNull(),implemented:integer("implemented",{mode:"boolean"}).notNull().default(false),health:text("health",{enum:["GREEN","YELLOW","RED"]}).notNull().default("YELLOW"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const crawlRuns=sqliteTable("crawl_runs",{id:text("id").primaryKey(),status:text("status",{enum:["RUNNING","SUCCESS","PARTIAL","FAILED"]}).notNull(),startedAt:text("started_at").notNull(),finishedAt:text("finished_at"),trigger:text("trigger").notNull(),errorCount:integer("error_count").notNull().default(0)});
export const sourceRuns=sqliteTable("source_runs",{id:text("id").primaryKey(),crawlRunId:text("crawl_run_id").notNull().references(()=>crawlRuns.id,{onDelete:"cascade"}),sourceId:text("source_id").notNull().references(()=>sources.id),status:text("status",{enum:["RUNNING","SUCCESS","FAILED","NOT_IMPLEMENTED"]}).notNull(),startedAt:text("started_at").notNull(),finishedAt:text("finished_at"),found:integer("found").notNull().default(0),inserted:integer("inserted").notNull().default(0),matched:integer("matched").notNull().default(0),error:text("error")},table=>[index("idx_source_runs_crawl_source").on(table.crawlRunId,table.sourceId),index("idx_source_runs_source_started").on(table.sourceId,table.startedAt)]);
export const rawNotices=sqliteTable("raw_notices",{id:text("id").primaryKey(),sourceId:text("source_id").notNull().references(()=>sources.id),sourceRunId:text("source_run_id").references(()=>sourceRuns.id),sourceNoticeId:text("source_notice_id"),title:text("title").notNull(),url:text("url").notNull(),publishedAt:text("published_at"),rawText:text("raw_text").notNull(),dedupeKey:text("dedupe_key").notNull(),collectedAt:text("collected_at").notNull()},table=>[uniqueIndex("uq_raw_notices_dedupe_key").on(table.dedupeKey),index("idx_raw_notices_source_collected").on(table.sourceId,table.collectedAt)]);
export const attachments=sqliteTable("attachments",{id:text("id").primaryKey(),rawNoticeId:text("raw_notice_id").notNull().references(()=>rawNotices.id,{onDelete:"cascade"}),name:text("name").notNull(),url:text("url").notNull(),contentType:text("content_type"),textExtracted:integer("text_extracted",{mode:"boolean"}).notNull().default(false),createdAt:text("created_at").notNull()},table=>[index("idx_attachments_raw_notice").on(table.rawNoticeId)]);
export const opportunities=sqliteTable("opportunities",{id:text("id").primaryKey(),dedupeKey:text("dedupe_key").notNull(),title:text("title").notNull(),organization:text("organization").notNull(),region:text("region").notNull(),field:text("field"),facilityTypesJson:text("facility_types_json").notNull().default("[]"),applicationStart:text("application_start"),deadline:text("deadline"),deadlineVerification:text("deadline_verification").notNull(),deadlineEvidence:text("deadline_evidence"),deadlineEvidenceLocation:text("deadline_evidence_location"),eligibilityVerification:text("eligibility_verification").notNull(),eligibilityEvidence:text("eligibility_evidence"),eligibilityEvidenceLocation:text("eligibility_evidence_location"),amountWon:integer("amount_won"),amountText:text("amount_text"),selfBurden:text("self_burden"),supportDetails:text("support_details"),reviewStatus:text("review_status").notNull(),publishedAt:text("published_at"),updatedAt:text("updated_at").notNull()},table=>[uniqueIndex("uq_opportunities_dedupe_key").on(table.dedupeKey),index("idx_opportunities_public_region").on(table.reviewStatus,table.region),index("idx_opportunities_deadline").on(table.deadlineVerification,table.deadline)]);
export const opportunitySources=sqliteTable("opportunity_sources",{opportunityId:text("opportunity_id").notNull().references(()=>opportunities.id,{onDelete:"cascade"}),rawNoticeId:text("raw_notice_id").notNull().references(()=>rawNotices.id,{onDelete:"cascade"}),isPrimary:integer("is_primary",{mode:"boolean"}).notNull().default(false),createdAt:text("created_at").notNull()},table=>[primaryKey({columns:[table.opportunityId,table.rawNoticeId]}),index("idx_opportunity_sources_raw").on(table.rawNoticeId)]);
export const collectionLocks=sqliteTable("collection_locks",{name:text("name").primaryKey(),holder:text("holder").notNull(),acquiredAt:text("acquired_at").notNull(),expiresAt:text("expires_at").notNull()});
export const savedOpportunities=sqliteTable("saved_opportunities",{id:text("id").primaryKey(),visitorKey:text("visitor_key").notNull(),opportunityId:text("opportunity_id").notNull().references(()=>opportunities.id,{onDelete:"cascade"}),createdAt:text("created_at").notNull()},table=>[uniqueIndex("uq_saved_visitor_opportunity").on(table.visitorKey,table.opportunityId)]);
